In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('glass.csv')
df

RI     Na    Mg    Al     Si     K    Ca    Ba   Fe  Type
0    1.52101  13.64  4.49  1.10  71.78  0.06  8.75  0.00  0.0     1
1    1.51761  13.89  3.60  1.36  72.73  0.48  7.83  0.00  0.0     1
2    1.51618  13.53  3.55  1.54  72.99  0.39  7.78  0.00  0.0     1
3    1.51766  13.21  3.69  1.29  72.61  0.57  8.22  0.00  0.0     1
4    1.51742  13.27  3.62  1.24  73.08  0.55  8.07  0.00  0.0     1
..       ...    ...   ...   ...    ...   ...   ...   ...  ...   ...
209  1.51623  14.14  0.00  2.88  72.61  0.08  9.18  1.06  0.0     7
210  1.51685  14.92  0.00  1.99  73.06  0.00  8.40  1.59  0.0     7
211  1.52065  14.36  0.00  2.02  73.42  0.00  8.44  1.64  0.0     7
212  1.51651  14.38  0.00  1.94  73.61  0.00  8.48  1.57  0.0     7
213  1.51711  14.23  0.00  2.08  73.36  0.00  8.62  1.67  0.0     7

[214 rows x 10 columns]

In [3]:
mew = df.drop(columns=['Type']).mean()
mew = mew.to_numpy()
print(mew)

[1.51836542e+00 1.34078505e+01 2.68453271e+00 1.44490654e+00
 7.26509346e+01 4.97056075e-01 8.95696262e+00 1.75046729e-01
 5.70093458e-02]


In [4]:
cov_inv = np.linalg.inv(np.cov(df.drop(columns=['Type']).to_numpy().T))
cov_inv

array([[ 1.03058131e+06, -1.43792755e+03, -1.90063017e+03,
        -3.36212885e+01, -1.73658752e+02, -1.42515573e+03,
        -3.21208258e+03, -3.07402374e+03, -4.39309210e+02],
       [-1.43792755e+03,  9.26601822e+01,  9.48853177e+01,
         9.19666479e+01,  9.23373822e+01,  9.56540223e+01,
         9.59362517e+01,  9.29969936e+01,  3.90532970e+01],
       [-1.90063017e+03,  9.48853177e+01,  9.98977666e+01,
         9.65617215e+01,  9.59183136e+01,  9.90388087e+01,
         1.00920367e+02,  9.90910357e+01,  3.67892977e+01],
       [-3.36212885e+01,  9.19666479e+01,  9.65617215e+01,
         1.03031563e+02,  9.52192851e+01,  9.46568042e+01,
         9.52720923e+01,  9.05947385e+01,  3.61476134e+01],
       [-1.73658752e+02,  9.23373822e+01,  9.59183136e+01,
         9.52192851e+01,  9.69739462e+01,  9.70175432e+01,
         9.52217523e+01,  9.36510960e+01,  3.77775902e+01],
       [-1.42515573e+03,  9.56540223e+01,  9.90388087e+01,
         9.46568042e+01,  9.70175432e+01,  1.025516

In [5]:
x = df.drop(columns=['Type']).to_numpy()
x

array([[ 1.52101, 13.64   ,  4.49   , ...,  8.75   ,  0.     ,  0.     ],
       [ 1.51761, 13.89   ,  3.6    , ...,  7.83   ,  0.     ,  0.     ],
       [ 1.51618, 13.53   ,  3.55   , ...,  7.78   ,  0.     ,  0.     ],
       ...,
       [ 1.52065, 14.36   ,  0.     , ...,  8.44   ,  1.64   ,  0.     ],
       [ 1.51651, 14.38   ,  0.     , ...,  8.48   ,  1.57   ,  0.     ],
       [ 1.51711, 14.23   ,  0.     , ...,  8.62   ,  1.67   ,  0.     ]])

In [6]:
print((x-mew).shape)
print((x-mew).T.shape)
print(cov_inv.shape)

(214, 9)
(9, 214)
(9, 9)


In [7]:
print((x[0]-mew).reshape(1,-1).shape)
print((x[0]-mew).reshape(-1,1).shape)
print(cov_inv.shape)

(1, 9)
(9, 1)
(9, 9)


In [8]:
distance = []
for i in x:
    x_ = (i-mew).reshape(9,1)
    d = np.sqrt(np.dot(np.dot(x_.T, cov_inv), x_))
    distance.append(d[0])
distance = np.array(distance)
distance

array([[2.19313092],
       [1.59918789],
       [1.3835073 ],
       [2.50289121],
       [1.34550441],
       [2.44744587],
       [1.39684586],
       [1.58391194],
       [1.86838199],
       [1.77689004],
       [2.30619262],
       [1.57657447],
       [2.28530121],
       [1.80391866],
       [1.81511641],
       [1.54498811],
       [1.93673915],
       [2.8015078 ],
       [1.57632799],
       [2.0919544 ],
       [1.73889108],
       [3.5608793 ],
       [1.43847933],
       [1.95029466],
       [1.12887921],
       [1.50964054],
       [1.17664837],
       [1.55365853],
       [1.70126   ],
       [1.04520646],
       [1.9404724 ],
       [1.52963537],
       [2.01149334],
       [2.34600753],
       [1.36447561],
       [2.49208361],
       [1.86500342],
       [1.34847742],
       [2.77613458],
       [2.77613458],
       [1.44718737],
       [1.50779559],
       [0.97269955],
       [2.32609031],
       [2.65933263],
       [1.36685646],
       [1.5668403 ],
       [4.917

In [9]:
import math
distance_thresholds = np.arange(min(distance)+0.1, max(distance)-0.1, 0.1)
# print(distance_thresholds)

min_var = 10
min_threshold = 0

for t in distance_thresholds:
    inliers = []
    outliers = []

    for i in range(len(distance)):
        if distance[i] < t:
            inliers.append(distance[i])
        else:
            outliers.append(distance[i])

    w0 = len(inliers)/len(distance)
    w1 = len(outliers)/len(distance)

    sig0_2 = np.var(inliers)
    sig1_2 = np.var(outliers)
    sig_2 = w0 * sig0_2 + w1 * sig1_2
    if sig_2 < min_var:
        min_var = sig_2
        min_threshold = t

print(min_threshold, min_var)

3.8929436430605717 0.8122610103305334


In [10]:
count = 0
for i in distance:
    if i > min_threshold:
        count += 1

In [11]:
count

29

LOF


In [12]:
# Implementing local outlier factor
k = 3
distance_matrix = np.zeros((214,214))

for i in range(214):
    for j in range(214):
        distance_matrix[i][j] = np.sqrt(np.sum((x[i] - x[j])**2))#np.linalg.norm(x[i]-x[j])
distance_matrix

array([[0.        , 1.68745713, 1.89821583, ..., 5.19651808, 5.22528662,
        5.17439999],
       [1.68745713, 0.        , 0.49264799, ..., 4.16949748, 4.1747696 ,
        4.1993214 ],
       [1.89821583, 0.49264799, 0.        , ..., 4.12116731, 4.12024272,
        4.14338037],
       ...,
       [5.19651808, 4.16949748, 4.12116731, ..., 0.        , 0.22229966,
        0.23960912],
       [5.22528662, 4.1747696 , 4.12024272, ..., 0.22229966, 0.        ,
        0.36633367],
       [5.17439999, 4.1993214 , 4.14338037, ..., 0.23960912, 0.36633367,
        0.        ]])

In [13]:
np.sort(distance_matrix[-1])

array([0.        , 0.23960912, 0.36633367, 0.38561649, 0.64288413,
       0.71603092, 0.79309524, 0.83504517, 0.86498557, 1.19327282,
       1.25147948, 1.25275743, 1.30407179, 1.30537457, 1.31965996,
       1.3793842 , 1.38369212, 1.43349368, 1.49519264, 1.521184  ,
       1.63740664, 2.06717221, 2.56885249, 2.8787852 , 2.88826941,
       2.901362  , 2.93496456, 2.95755   , 3.07262126, 3.09246063,
       3.15372986, 3.27214055, 3.35636784, 3.37409389, 3.38122877,
       3.38815645, 3.45384085, 3.46159019, 3.48775016, 3.50301494,
       3.51937803, 3.59135436, 3.59473232, 3.63302917, 3.6671108 ,
       3.68325947, 3.70410597, 3.77035808, 3.77710294, 3.82176665,
       3.87639008, 3.88028901, 3.94538987, 3.95934356, 3.96782059,
       4.00037517, 4.04760427, 4.07343841, 4.078186  , 4.08113176,
       4.10043912, 4.10192662, 4.10266991, 4.10385215, 4.12128638,
       4.12703308, 4.13038756, 4.13345003, 4.13347312, 4.13956528,
       4.14338037, 4.14397153, 4.14661321, 4.14721602, 4.14762

In [14]:
k_distance = []
knn = []
for i in range(214):
    knn.append(np.argsort(distance_matrix[i])[1:k+1])
    # print(knn)
    k_distance.append(distance_matrix[i][knn[i][-1]])

k_distance

[1.028352595222086,
 0.4927486053760078,
 0.4720172031822587,
 0.30000153599606794,
 0.3248076655499354,
 0.2877521893921927,
 0.28740217831464293,
 0.3500003571426761,
 0.6096724448423104,
 0.2489980082249653,
 0.3054518425218598,
 0.237276303283743,
 0.3509996047006323,
 0.2874021657886378,
 0.2519920641607617,
 0.2433108300096715,
 0.237276303283743,
 0.6033242048020276,
 0.6330086915674985,
 0.32249321992872926,
 0.3373435769360369,
 1.0052886600375017,
 0.22203643034421724,
 0.20420599893245123,
 0.27110904743294467,
 0.21260619087881724,
 0.2334523925771614,
 0.21863237546164413,
 0.27422618401604376,
 0.2224859602311998,
 0.23065130738844736,
 0.2875760770648356,
 0.2842534293548635,
 0.3200000006249989,
 0.2133078078739711,
 0.2224912153322021,
 0.5039858816474948,
 0.22803526942120397,
 0.4893881277677236,
 0.4893881277677236,
 0.2622975440220531,
 0.26476407781268424,
 0.2334523925771614,
 0.402890661222129,
 0.3321144454852868,
 0.34292923818187215,
 0.3545484164398424,
 0.4

In [15]:
knn = np.array(knn)
knn

array([[ 18,  71, 133],
       [ 78,   2, 119],
       [ 73,  81,  86],
       [147, 134, 148],
       [  6,  58,   7],
       [121, 142, 137],
       [  4,   7,  58],
       [  6,   4, 136],
       [ 36, 133,  71],
       [ 27,  57,  25],
       [ 12,   5, 142],
       [ 23,  25,  16],
       [ 10, 142, 138],
       [ 15,  27,   9],
       [ 33,  28,  15],
       [ 13,  31,  27],
       [ 30,  40,  11],
       [151, 162,  63],
       [ 65,  36,  60],
       [ 20, 143, 125],
       [125,  19, 126],
       [ 38,  39,  17],
       [126,  34, 154],
       [ 11,  37,  27],
       [ 35, 153,  59],
       [ 57,  29, 155],
       [148, 147,  42],
       [ 57,  23,   9],
       [ 14,  33,  30],
       [ 25, 155,  42],
       [ 34,  37,  16],
       [ 15,  41,  13],
       [ 44,  57,  25],
       [ 14,  28,  41],
       [ 37,  30,  22],
       [ 42, 156,  24],
       [ 49,  45, 158],
       [ 34,  23,  30],
       [ 39, 157, 151],
       [ 39, 157, 151],
       [ 16,  41,  37],
       [ 31,  40

In [16]:
reach_dist = np.zeros((214,214))
for i in range(214):
    for j in range(214):
        reach_dist[i][j] = max(k_distance[i], distance_matrix[i][j])
reach_dist

array([[1.0283526 , 1.68745713, 1.89821583, ..., 5.19651808, 5.22528662,
        5.17439999],
       [1.68745713, 0.49274861, 0.49274861, ..., 4.16949748, 4.1747696 ,
        4.1993214 ],
       [1.89821583, 0.49264799, 0.4720172 , ..., 4.12116731, 4.12024272,
        4.14338037],
       ...,
       [5.19651808, 4.16949748, 4.12116731, ..., 0.2733397 , 0.2733397 ,
        0.2733397 ],
       [5.22528662, 4.1747696 , 4.12024272, ..., 0.3780213 , 0.3780213 ,
        0.3780213 ],
       [5.17439999, 4.1993214 , 4.14338037, ..., 0.38561649, 0.38561649,
        0.38561649]])

In [17]:
lrd = [0 for i in range(214)]

for i in range(214):
    score = 0
    for j in knn[i]:
        score += reach_dist[j][i]
    lrd[i] = len(knn[i])/score
lrd

[1.0355880581542576,
 1.9162341249521295,
 2.418627684968793,
 3.5101258173869345,
 3.184593787424366,
 3.562938593365958,
 3.0629720673558354,
 3.0632209624806093,
 1.665860698886271,
 4.316498500752166,
 3.1611346309782604,
 4.4533773404077746,
 3.000109493094385,
 3.7650799608595444,
 3.5451847135745713,
 3.666186069799488,
 4.108321906900271,
 1.659957529741968,
 1.624807601415611,
 2.810912532541548,
 2.841731720876305,
 1.0984119337167708,
 3.4859330528944126,
 4.386324358950651,
 3.8176032490781613,
 4.330422429115472,
 4.253753741639444,
 4.490029220696031,
 3.545184713574571,
 4.277144162121135,
 4.420740235035365,
 3.77049743792543,
 3.3501809477356095,
 3.5451847135745713,
 4.407078897690157,
 3.572541381822112,
 2.0081189922962888,
 4.628450273394466,
 2.2699715487879644,
 2.2699715487879644,
 3.9249655177518097,
 3.682618670916474,
 4.42197707895071,
 2.3912910156786844,
 3.3175142015210395,
 3.018798486705751,
 2.9494947978835793,
 2.3719999140169996,
 2.2638465421378116,

In [18]:
lof = [0 for i in range(214)]

for i in range(214):
    score = 0
    for j in knn[i]:
        score += lrd[j]/lrd[i]
    lof[i] = score/len(knn[i])
lof

[1.604094821026049,
 1.3536540791971408,
 1.292402076628377,
 1.0797021887605676,
 0.9827514316475076,
 1.1203314695521513,
 1.0350093332388648,
 0.9845821743341916,
 1.0738904553211341,
 1.0396628159190595,
 1.0468856656256473,
 0.9599507455909154,
 1.070117797313177,
 1.104245144052686,
 1.0113770617519213,
 1.0933802768080012,
 1.03846804796364,
 1.1134359215767968,
 1.175988989637557,
 1.0157014636077246,
 1.075148006051984,
 1.881474043573335,
 1.0748553591207088,
 1.03137659414872,
 0.9627624214724236,
 1.0210613541459592,
 0.9753685062924203,
 0.9907493182883803,
 1.082323451122145,
 1.0207339686787684,
 0.9910746752181838,
 0.9825303676368046,
 1.2228786177195812,
 1.0129221247453073,
 0.948105222856661,
 1.1025444724340554,
 1.4558005532295777,
 0.9516607583632979,
 0.9255022871519634,
 0.9255022871519634,
 1.0547346038278016,
 1.0967017651868642,
 0.9123701208370436,
 0.9251603729787193,
 1.1751657003869909,
 0.9588092310311683,
 1.30774886151767,
 0.9398896873346061,
 0.9948

In [19]:
distance_thresholds = np.arange(min(lof) + 0.1, max(lof) - 0.1, 0.1)
# print(distance_thresholds)

min_var = 10000
min_threshold = 0

for t in distance_thresholds:
    inliers = []
    outliers = []

    for i in range(len(lof)):
        if lof[i] < t:
            inliers.append(lof[i])
        else:
            outliers.append(lof[i])

    w0 = len(inliers) / len(lof)
    w1 = len(outliers) / len(lof)

    sig0_2 = np.var(inliers)
    sig1_2 = np.var(outliers)
    sig_2 = w0 * sig0_2 + w1 * sig1_2
    if sig_2 < min_var:
        min_var = sig_2
        min_threshold = t

print(min_threshold, min_var)
count = 0
for i in lof:
    if i > min_threshold:
        count += 1

2.266759863388833 0.16211491849650794


In [20]:
count

9