In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('Heart.csv')
df['AHD'].replace({'Yes':1, 'No':0}, inplace=True)
df['ChestPain'].replace({'asymptomatic':0, 'nonanginal':1, 'nontypical':2, 'typical':3}, inplace=True)
df['Thal'].replace({'normal':0, 'fixed':1, 'reversable':2}, inplace=True)
df = df.drop(index=[87, 166, 192, 266, 287, 302])
df = df.drop(columns='Unnamed: 0')
df

Age  Sex  ChestPain  RestBP  Chol  Fbs  RestECG  MaxHR  ExAng  Oldpeak  \
0     63    1          3     145   233    1        2    150      0      2.3   
1     67    1          0     160   286    0        2    108      1      1.5   
2     67    1          0     120   229    0        2    129      1      2.6   
3     37    1          1     130   250    0        0    187      0      3.5   
4     41    0          2     130   204    0        2    172      0      1.4   
..   ...  ...        ...     ...   ...  ...      ...    ...    ...      ...   
297   57    0          0     140   241    0        0    123      1      0.2   
298   45    1          3     110   264    0        0    132      0      1.2   
299   68    1          0     144   193    1        0    141      0      3.4   
300   57    1          0     130   131    0        0    115      1      1.2   
301   57    0          2     130   236    0        2    174      0      0.0   

     Slope   Ca  Thal  AHD  
0        3  0.0   1.0    0  
1        2  3.0   0.0    1  
2        2  2.0   2.0    1  
3        3  0.0   0.0    0  
4        1  0.0   0.0    0  
..     ...  ...   ...  ...  
297      2  0.0   2.0    1  
298      2  0.0   2.0    1  
299      2  2.0   2.0    1  
300      2  1.0   2.0    1  
301      2  1.0   0.0    1  

[297 rows x 14 columns]

In [3]:
#88, 167, 193, 267, 288, 303 rows dropped

In [4]:
data_x = df.drop(columns='AHD').to_numpy()
data_y = df['AHD'].to_numpy()

In [5]:
data_x

array([[63.,  1.,  3., ...,  3.,  0.,  1.],
       [67.,  1.,  0., ...,  2.,  3.,  0.],
       [67.,  1.,  0., ...,  2.,  2.,  2.],
       ...,
       [68.,  1.,  0., ...,  2.,  2.,  2.],
       [57.,  1.,  0., ...,  2.,  1.,  2.],
       [57.,  0.,  2., ...,  2.,  1.,  0.]])

In [6]:
data_y

array([0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1,
       1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1,
       0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1,
       0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1])

In [7]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(data_x, data_y, test_size=0.3, random_state=25)

In [8]:
clusters = {0:[], 1:[]}
c0 = []
c1 = []
for i in range(len(x_train)):
    if y_train[i] == 0:
        clusters[0].append(i)
        c0.append(x_train[i])
    else:
        clusters[1].append([i])
        c1.append(x_train[i])

c0 = np.array(c0)
c1 = np.array(c1)

In [9]:
c0

array([[58.,  0.,  1., ...,  1.,  0.,  0.],
       [51.,  0.,  1., ...,  1.,  1.,  0.],
       [55.,  0.,  2., ...,  2.,  0.,  0.],
       ...,
       [70.,  1.,  2., ...,  1.,  0.,  0.],
       [58.,  1.,  1., ...,  2.,  0.,  2.],
       [51.,  1.,  0., ...,  1.,  0.,  0.]])

In [10]:
c1.shape

(94, 13)

In [11]:
m0 = np.mean(c0, axis=0)
m0

array([5.23185841e+01, 5.66371681e-01, 1.12389381e+00, 1.29557522e+02,
       2.44247788e+02, 1.32743363e-01, 8.58407080e-01, 1.60256637e+02,
       1.76991150e-01, 6.04424779e-01, 1.38938053e+00, 2.74336283e-01,
       3.36283186e-01])

In [12]:
s0 = np.zeros((13,13))
for i in range(len(c0)):
    s0 += np.matmul((c0-m0).T, (c0-m0))
s0 = s0/(len(c0)-1)
s0

array([[ 1.01604464e+04, -1.06330357e+02, -1.05535714e+01,
         4.53001786e+03,  1.30142500e+04,  2.54464286e+01,
         1.42357143e+02, -1.16715268e+04,  2.58571429e+01,
         7.89392857e+01,  4.94196429e+01,  1.14133929e+02,
         8.16160714e+01],
       [-1.06330357e+02,  2.80000000e+01, -9.37500000e-01,
        -1.69642857e+00, -6.62723214e+02,  2.52678571e+00,
         3.08928571e+00,  2.00348214e+02,  6.78571429e-01,
         3.44732143e+00, -1.93750000e+00, -3.58928571e+00,
         1.46071429e+01],
       [-1.05535714e+01, -9.37500000e-01,  9.10714286e+01,
         1.72723214e+02, -4.58526786e+02,  2.16071429e+00,
         6.03571429e+00,  5.59017857e+01, -1.49107143e+00,
         1.24482143e+01,  1.56250000e+00,  1.60714286e-01,
        -2.73214286e+00],
       [ 4.53001786e+03, -1.69642857e+00,  1.72723214e+02,
         2.97935357e+04,  6.59676786e+03,  4.90714286e+01,
         1.84553571e+02, -6.17633929e+02, -1.12500000e+01,
         3.49615179e+02,  2.97321429e

In [13]:
m1 = np.mean(c1, axis=0)
m1

array([5.60319149e+01, 8.40425532e-01, 3.72340426e-01, 1.32340426e+02,
       2.48861702e+02, 1.48936170e-01, 1.21276596e+00, 1.37446809e+02,
       5.31914894e-01, 1.40531915e+00, 1.80851064e+00, 1.07446809e+00,
       1.39361702e+00])

In [14]:
s1 = np.zeros((13,13))
for i in range(len(c1)):
    s1 += np.matmul((c1-m1).T, (c1-m1))
s1 = s1/(len(c1)-1)
s1.shape

(13, 13)

In [15]:
n0 = len(c0)
n1 = len(c1)
inverse_s = np.linalg.inv(n0*s0 + n1*s1)
inverse_s

array([[ 8.05816968e-07,  1.18995021e-06, -3.44029600e-07,
        -1.05004417e-07, -1.91114306e-08,  1.13506902e-07,
        -5.52263602e-07,  1.40219481e-07,  1.19361185e-06,
         5.97240496e-07, -2.94531727e-07, -1.62615034e-06,
        -1.63967058e-07],
       [ 1.18995021e-06,  2.78404642e-04, -3.57608568e-06,
         6.94906204e-07,  4.94964282e-07, -2.28132685e-05,
        -1.02029775e-05, -3.20525573e-07,  5.05843349e-07,
        -6.19384788e-06,  2.96367166e-05,  7.59266213e-06,
        -4.77037575e-05],
       [-3.44029600e-07, -3.57608568e-06,  6.78015901e-05,
        -2.03310507e-07,  5.91116618e-08, -1.16598256e-06,
        -6.26628699e-07, -2.94378516e-07,  2.70701053e-05,
        -2.35185215e-06, -2.28310294e-06,  3.17505818e-06,
         7.40609304e-06],
       [-1.05004417e-07,  6.94906204e-07, -2.03310507e-07,
         1.98494762e-07, -2.70052172e-09, -1.54402196e-06,
        -1.67849138e-07, -2.31762333e-08, -1.83093680e-07,
        -9.09950816e-07,  3.70168574e

In [27]:
omega = np.matmul(inverse_s, (m0-m1))
print(omega)

[ 8.91689371e-07 -5.42248404e-05  2.98948172e-05 -4.91559599e-07
 -1.42704093e-07  3.11790095e-05 -1.57504771e-05  2.09954476e-06
 -3.15292758e-05  1.26396967e-06 -3.18017904e-05 -6.33078368e-05
 -5.58083008e-05]


In [17]:
projected_train_data = np.matmul(omega, x_train.T)
print(projected_train_data.shape)

(207,)


In [18]:
def sigmoid(z):
    return 1 / (1 + np.exp(-z))

In [19]:
theta = np.zeros(2)
theta = theta.reshape(-1,1)
print(theta)

[[0.]
 [0.]]


In [20]:
xes = []
for i in projected_train_data:
    # print(i)
    xes.append([1.0,i])
xes = np.array(xes)
print(len(xes))

yes = np.array(y_train).reshape(-1,1)
print(yes)

207
[[1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [1]
 [0]
 [1]
 [1]
 [0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [1]
 [1]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [1]
 [0]
 [1]
 [1]
 [0]
 [0]
 [1]
 [0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]
 [1]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [0]
 [1]
 [1]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [0]
 [1]
 [1]
 [0]
 [0]
 [1]
 [0]
 [1]
 [1]
 [0]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [1]
 [1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [1]
 [1]
 [1]
 [0]
 [1]
 [1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [1]
 [1]
 [0]
 [1]
 [0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [1]
 [1]
 [1]
 [0]
 [1]
 [1]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 

In [21]:
number_of_iterations = 500000
learning_rate = 0.1
print(theta)
# theta[0][0] = -1.11
# theta[1][0] = -103.8
# while True:
for i in range(number_of_iterations):
    # p = sigmoid(np.dot(xes, theta))
    # otheta = theta
    d = np.matmul((sigmoid(np.dot(xes, theta)) - yes).T, xes)
    theta = theta - (learning_rate/len(xes))*(d.T)#np.dot(xes.T, (sigmoid(np.dot(xes, theta)) - yes))#np.dot(xes.T,p-yes)
    # if otheta[0]-theta[0] < 0.000001:
    #     break
# print(p)
print(theta)
# theta[0][0] = -1.11
# theta[1][0] = -103.8
print(theta)


[[0.]
 [0.]]
[[-0.1838396 ]
 [-2.75348089]]
[[-0.1838396 ]
 [-2.75348089]]


In [22]:
# [[-0.18398268]
 # [-1.66875326]]
projected_test_data = np.matmul(omega, x_test.T)
# print(y_test.reshape(-1,1))
# print(y_test)
print(projected_test_data)

[ 2.41370280e-04 -2.39050129e-04  2.76139361e-04 -9.65467920e-05
 -2.37455053e-05 -9.87200906e-05  2.51826636e-04  2.82923463e-04
  2.26422063e-05 -2.23636729e-06 -1.03390607e-04  1.94736807e-04
 -1.10191474e-04  1.22708434e-04 -8.15359726e-05  1.84111879e-04
 -1.38257747e-04  3.02923028e-04 -7.13064586e-05  2.18655971e-04
  1.87854226e-04  1.00050272e-04  1.90671801e-05 -2.03915126e-04
  9.49238473e-06 -1.19226391e-04 -8.24170454e-05  2.75374282e-04
  2.75694330e-04  2.83818916e-04 -1.12514845e-04  1.69601881e-04
  2.29837259e-04  5.29666617e-05  1.95009753e-04  2.98339611e-04
 -3.73269690e-06  3.51771536e-05  1.78825869e-04  2.12571307e-04
 -1.61314479e-04  1.51318862e-04  1.11501872e-04 -1.22247688e-04
  1.29475304e-04  3.49401861e-04  2.50359611e-05  1.57562783e-04
  1.68069550e-04  1.32877282e-04  1.11293597e-04  1.95779138e-04
  1.04522608e-04  1.03253266e-06  1.76697596e-04  1.59568892e-04
 -2.01855092e-04  2.60945316e-04  9.60354531e-05 -1.26361369e-04
  7.00603771e-05  2.41403

In [23]:
xes_test = []
for i in projected_test_data:
    # print(i)
    xes_test.append([1.0,i])
xes_test = np.array(xes_test)
print(xes_test.shape)

# yes_test = np.array(y_t).reshape(-1,1)
# print(yes_test)

(90, 2)


In [24]:
y_pred = sigmoid(np.dot(xes_test, theta))
print(y_pred)
final_y = [1 if i >= 0.5 else 0 for i in y_pred]
len(final_y)

[[0.45400436]
 [0.45433228]
 [0.45398062]
 [0.45423501]
 [0.45418532]
 [0.45423649]
 [0.45399722]
 [0.45397599]
 [0.45415365]
 [0.45417063]
 [0.45423968]
 [0.45403619]
 [0.45424432]
 [0.45408535]
 [0.45422476]
 [0.45404344]
 [0.45426348]
 [0.45396234]
 [0.45421778]
 [0.45401986]
 [0.45404088]
 [0.45410081]
 [0.45415609]
 [0.4543083 ]
 [0.45416263]
 [0.45425049]
 [0.45422536]
 [0.45398115]
 [0.45398093]
 [0.45397538]
 [0.45424591]
 [0.45405334]
 [0.45401223]
 [0.45413295]
 [0.454036  ]
 [0.45396547]
 [0.45417165]
 [0.4541451 ]
 [0.45404705]
 [0.45402401]
 [0.45427922]
 [0.45406582]
 [0.454093  ]
 [0.45425255]
 [0.45408073]
 [0.45393062]
 [0.45415202]
 [0.45406156]
 [0.45405439]
 [0.45407841]
 [0.45409314]
 [0.45403547]
 [0.45409776]
 [0.4541684 ]
 [0.4540485 ]
 [0.45406019]
 [0.45430689]
 [0.453991  ]
 [0.45410356]
 [0.45425536]
 [0.45412129]
 [0.45400433]
 [0.45410758]
 [0.45405177]
 [0.4542911 ]
 [0.45426733]
 [0.45399483]
 [0.45414798]
 [0.45427478]
 [0.45414908]
 [0.45406882]
 [0.45

90

In [25]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test, final_y))

0.5222222222222223
