In [25]:
import pandas as pd
import numpy as np

df = pd.read_csv('Heart.csv')
df = df.dropna()
df = df.drop(['Unnamed: 0'], axis=1)
df.shape

(297, 14)

In [26]:
df.shape

(297, 14)

In [27]:
df['ChestPain'] = df['ChestPain'].map({'typical':0, 'asymptomatic':1, 'nonanginal':2, 'nontypical':3})
df['Thal'] = df['Thal'].map({'fixed':0, 'normal':1, 'reversable':2})
df['AHD'] = df['AHD'].map({'Yes': 1, 'No': 0})

In [28]:
df

Age  Sex  ChestPain  RestBP  Chol  Fbs  RestECG  MaxHR  ExAng  Oldpeak  \
0     63    1          0     145   233    1        2    150      0      2.3   
1     67    1          1     160   286    0        2    108      1      1.5   
2     67    1          1     120   229    0        2    129      1      2.6   
3     37    1          2     130   250    0        0    187      0      3.5   
4     41    0          3     130   204    0        2    172      0      1.4   
..   ...  ...        ...     ...   ...  ...      ...    ...    ...      ...   
297   57    0          1     140   241    0        0    123      1      0.2   
298   45    1          0     110   264    0        0    132      0      1.2   
299   68    1          1     144   193    1        0    141      0      3.4   
300   57    1          1     130   131    0        0    115      1      1.2   
301   57    0          3     130   236    0        2    174      0      0.0   

     Slope   Ca  Thal  AHD  
0        3  0.0     0    0  
1        2  3.0     1    1  
2        2  2.0     2    1  
3        3  0.0     1    0  
4        1  0.0     1    0  
..     ...  ...   ...  ...  
297      2  0.0     2    1  
298      2  0.0     2    1  
299      2  2.0     2    1  
300      2  1.0     2    1  
301      2  1.0     1    1  

[297 rows x 14 columns]

In [29]:
df_c1 = df[df.AHD == 1]
df_c2 = df[df.AHD == 0]

df_c1_x = df_c1.drop(columns=['AHD'])
df_c2_x = df_c2.drop(columns=['AHD'])

df_c1_y = df_c1['AHD']
df_c2_y = df_c2['AHD']

In [30]:
m1 = df_c1_x.mean()
m1 = m1.to_numpy()
m1

array([5.67591241e+01, 8.17518248e-01, 1.21167883e+00, 1.34635036e+02,
       2.51854015e+02, 1.45985401e-01, 1.17518248e+00, 1.39109489e+02,
       5.40145985e-01, 1.58905109e+00, 1.82481752e+00, 1.14598540e+00,
       1.55474453e+00])

In [31]:
m2 = df_c2_x.mean()
m2 = m2.to_numpy()
m2

array([5.2643750e+01, 5.5625000e-01, 1.8062500e+00, 1.2917500e+02,
       2.4349375e+02, 1.4375000e-01, 8.4375000e-01, 1.5858125e+02,
       1.4375000e-01, 5.9875000e-01, 1.4125000e+00, 2.7500000e-01,
       1.1312500e+00])

In [32]:
x1 = df_c1_x.to_numpy()
x1

array([[67.,  1.,  1., ...,  2.,  3.,  1.],
       [67.,  1.,  1., ...,  2.,  2.,  2.],
       [62.,  0.,  1., ...,  3.,  2.,  1.],
       ...,
       [68.,  1.,  1., ...,  2.,  2.,  2.],
       [57.,  1.,  1., ...,  2.,  1.,  2.],
       [57.,  0.,  3., ...,  2.,  1.,  1.]])

In [33]:
x2 = df_c2_x.to_numpy()
x2

array([[63.,  1.,  0., ...,  3.,  0.,  0.],
       [37.,  1.,  2., ...,  3.,  0.,  1.],
       [41.,  0.,  3., ...,  1.,  0.,  1.],
       ...,
       [56.,  1.,  3., ...,  3.,  0.,  1.],
       [55.,  0.,  3., ...,  1.,  0.,  1.],
       [41.,  1.,  3., ...,  1.,  0.,  1.]])

In [34]:
y1 = df_c1_y.to_numpy()
y1

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1])

In [35]:
y2 = df_c2_y.to_numpy()
y2

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0])

FDA

In [36]:
s1 = (1/(len(x1)))*np.matmul((x1-m1).T, (x1-m1))
s1.shape

(13, 13)

In [37]:
s2 = (1/(len(x2)))*np.matmul((x2-m2).T, (x2-m2))
s2.shape

(13, 13)

In [38]:
n1 = len(x1)
n2 = len(x2)
print(n1, n2)
# omega = ()

137 160


In [39]:
omega = np.matmul(np.linalg.inv(n1*s1 + n2*s2), (m1-m2))

In [40]:
omega

array([-5.37026734e-05,  4.85394342e-03, -1.18709383e-03,  5.82838617e-05,
        1.03012462e-05, -2.62067835e-03,  7.73717781e-04, -9.89388727e-05,
        4.90358265e-03,  8.42040658e-04,  2.20755602e-03,  4.46695857e-03,
        4.14407209e-03])

In [41]:
px1 = np.matmul(x1, omega)
print(px1)

[ 3.13290856e-02  2.69362020e-02  1.48530346e-02  1.58294927e-02
  1.70874544e-02  8.85474206e-03  6.61626607e-03  3.88959745e-03
  1.59211076e-02  2.71928059e-02  1.92095998e-02  1.66943466e-02
  1.37272901e-03  1.95617300e-02  1.69486799e-02  2.20673272e-02
  2.35971687e-02 -2.30824945e-03  1.27599179e-02  1.60033198e-02
  8.04746059e-03  1.74257072e-02  2.54236209e-02  1.19029560e-02
  6.05887300e-03  1.13608197e-02  3.16841453e-02  1.68665820e-02
  2.81973861e-02  6.62028295e-03  2.41381811e-02  8.17811613e-03
  1.30286366e-02  2.83432608e-02  6.70390090e-03  4.59834403e-03
  2.24164592e-02  1.87141463e-02  1.51816408e-02  2.72318017e-02
  1.48985456e-02  1.99539764e-02  1.68315582e-02  2.28147324e-02
  1.43195971e-02  1.34516588e-02  2.13170756e-02  1.05681768e-02
  1.27019253e-02  1.41297266e-02  1.33139173e-02  1.31659693e-02
  2.74425522e-02  1.91711411e-02  1.97222686e-02  2.41479679e-02
  2.46559213e-02  8.22778698e-03  2.83134495e-02  2.16053412e-02
  1.97875808e-02  1.75576

In [42]:
px2 = np.matmul(x2, omega)
print(px2)

[ 4.96731320e-03  5.85728368e-03 -4.02430035e-03 -2.87538897e-03
  2.02595725e-03  8.52352265e-04  6.83300859e-04  2.01231069e-03
  4.02993377e-03  3.75421316e-04  2.92050098e-03 -1.77463831e-03
 -1.08343027e-03  1.22804379e-02 -1.36459452e-03 -1.53517770e-03
 -5.65831359e-03  9.20329883e-03  3.34076357e-03  8.77770268e-03
  7.97232285e-03  3.97589933e-03  6.39668360e-04  8.57917831e-03
  1.18825455e-02  4.65648708e-03 -2.17446708e-04  2.64223346e-03
  1.47607229e-03  4.90499911e-03 -3.40678279e-03  5.97463409e-03
 -1.93882514e-03  1.18409803e-02  1.76758580e-02  7.82151397e-03
 -7.36289044e-03  7.77776660e-03 -1.67752015e-03  8.01931501e-04
  5.79926378e-03  1.28167170e-03  1.23477813e-02  2.55827266e-03
  1.74398101e-03 -1.65535852e-03  7.87438220e-04  3.11092284e-03
 -1.51082695e-03 -1.32081098e-03  5.73117908e-03  2.22814096e-02
 -5.23986670e-03 -4.41164313e-03  4.24058820e-03 -1.69375953e-05
  2.26569619e-04  2.46407484e-03  2.96820717e-03 -1.62731984e-04
  2.93169577e-03 -1.98090

In [43]:
def sig(x):
    return 1/(1+np.exp(-x))

In [44]:
px = []
py = []
for i in px1:
    px.append([1,i])
for i in y1:
    py.append(i)
for i in px2:
    px.append([1,i])
for i in y2:
    py.append(i)
px = np.array(px)
py = np.array(py)
print(px)
print(py)

[[ 1.00000000e+00  3.13290856e-02]
 [ 1.00000000e+00  2.69362020e-02]
 [ 1.00000000e+00  1.48530346e-02]
 [ 1.00000000e+00  1.58294927e-02]
 [ 1.00000000e+00  1.70874544e-02]
 [ 1.00000000e+00  8.85474206e-03]
 [ 1.00000000e+00  6.61626607e-03]
 [ 1.00000000e+00  3.88959745e-03]
 [ 1.00000000e+00  1.59211076e-02]
 [ 1.00000000e+00  2.71928059e-02]
 [ 1.00000000e+00  1.92095998e-02]
 [ 1.00000000e+00  1.66943466e-02]
 [ 1.00000000e+00  1.37272901e-03]
 [ 1.00000000e+00  1.95617300e-02]
 [ 1.00000000e+00  1.69486799e-02]
 [ 1.00000000e+00  2.20673272e-02]
 [ 1.00000000e+00  2.35971687e-02]
 [ 1.00000000e+00 -2.30824945e-03]
 [ 1.00000000e+00  1.27599179e-02]
 [ 1.00000000e+00  1.60033198e-02]
 [ 1.00000000e+00  8.04746059e-03]
 [ 1.00000000e+00  1.74257072e-02]
 [ 1.00000000e+00  2.54236209e-02]
 [ 1.00000000e+00  1.19029560e-02]
 [ 1.00000000e+00  6.05887300e-03]
 [ 1.00000000e+00  1.13608197e-02]
 [ 1.00000000e+00  3.16841453e-02]
 [ 1.00000000e+00  1.68665820e-02]
 [ 1.00000000e+00  2

In [45]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(px, py, test_size=0.1, random_state=42)

In [46]:
weight = np.zeros(2)
print(weight.reshape(-1,1))

[[0.]
 [0.]]


In [47]:
max_iter = 500000
learning_rate = 0.1
weight = np.zeros(2)

for _ in range(max_iter):
    p = sig(np.dot(x_train, weight))
    weight = weight - (learning_rate/(n1+n2))*np.matmul(x_train.T, (p-y_train))

print(weight)

[-1.02020837 97.66487273]


In [48]:
y_pred = sig(np.dot(x_test, weight))
y_final = [1 if i > 0.5 else 0 for i in y_pred]
y_final

[0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0]

In [49]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test, y_final))

0.9


PCA+FDA

In [50]:
from sklearn.decomposition import PCA
import numpy as np

pca = PCA(n_components=13)

x = np.concatenate((x1, x2), axis=0)
y = np.concatenate((y1, y2), axis=0)

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.1, random_state=42)
pca.fit(x_train)
x_train = pca.transform(x_train)

print(x_train)


[[-2.90792233e+01  4.61235713e+01  1.25701389e+01 ...  9.32489665e-02
  -7.33947103e-01 -2.43206662e-01]
 [ 5.09033443e+01 -2.68884411e+01  2.06441983e+01 ... -2.69320323e-01
  -6.69223654e-01  7.11541350e-01]
 [-7.71325714e+01 -1.09855870e+01 -1.80896331e+01 ...  3.11636012e-01
  -4.16611662e-01 -1.28604344e-02]
 ...
 [-1.34499897e+01  6.44873278e+00  4.17353546e+00 ... -2.73331923e-01
  -4.66791409e-01 -2.72129507e-01]
 [ 2.08723036e+01 -1.39766006e+01 -1.47534664e+00 ...  5.07717207e-01
  -4.98722174e-02 -4.64521840e-02]
 [-9.94750938e+01  2.26089345e+01 -1.09738309e+01 ...  9.61839051e-02
  -2.28463165e-01 -1.97897200e-01]]


In [51]:
c0_x = [x_train[i] for i in range(len(x_train)) if y_train[i] == 1]
c0_x = np.array(c0_x)
c0_y = [i for i in y_train if i == 1]
print(c0_x)
print(c0_y)

[[-2.90792233e+01  4.61235713e+01  1.25701389e+01 ...  9.32489665e-02
  -7.33947103e-01 -2.43206662e-01]
 [-7.71325714e+01 -1.09855870e+01 -1.80896331e+01 ...  3.11636012e-01
  -4.16611662e-01 -1.28604344e-02]
 [ 5.84433575e+01 -8.48651369e+00  2.57280316e+01 ...  4.51337070e-01
  -6.89182088e-02 -1.91069638e-01]
 ...
 [ 5.19760661e+01 -2.08255442e+01 -5.84750709e+00 ...  2.70670695e-03
  -3.79936948e-01 -2.41224597e-01]
 [-1.34499897e+01  6.44873278e+00  4.17353546e+00 ... -2.73331923e-01
  -4.66791409e-01 -2.72129507e-01]
 [-9.94750938e+01  2.26089345e+01 -1.09738309e+01 ...  9.61839051e-02
  -2.28463165e-01 -1.97897200e-01]]
[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 

In [52]:
c1_x = [x_train[i] for i in range(len(x_train)) if y_train[i] == 0]
c1_x = np.array(c1_x)
c1_y = [i for i in y_train if i == 0]
print(c1_x)
print(c1_y)

[[ 5.09033443e+01 -2.68884411e+01  2.06441983e+01 ... -2.69320323e-01
  -6.69223654e-01  7.11541350e-01]
 [ 6.65637332e+01 -1.43935424e+01 -4.59047951e+00 ... -3.82136410e-01
  -1.78050552e-01 -6.11056018e-02]
 [ 5.50435718e+01 -9.05471839e+00 -4.31010880e+00 ...  5.38083945e-01
  -8.37720229e-02 -1.15145595e-01]
 ...
 [-9.16543576e+01 -3.37779309e+01 -5.30250014e+00 ... -2.23443140e-01
   1.12783825e-01 -9.97343863e-02]
 [-1.65734380e+01  5.37693314e+00  6.03770575e-01 ...  2.40612542e-02
  -4.03826858e-01 -3.52293820e-01]
 [ 2.08723036e+01 -1.39766006e+01 -1.47534664e+00 ...  5.07717207e-01
  -4.98722174e-02 -4.64521840e-02]]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

In [53]:
m0 = np.mean(c0_x, axis=0)
m0

array([ 4.13348247e+00,  1.06826524e+01,  2.06188680e+00, -1.12381628e-02,
        5.08107553e-01,  8.83361720e-03,  2.26109637e-01,  2.17655920e-02,
       -1.30685492e-01,  4.39450951e-02, -4.65436265e-02,  3.66067616e-02,
       -2.91777215e-02])

In [54]:
m1 = np.mean(c1_x, axis=0)
m1

array([-3.58427850e+00, -9.26327902e+00, -1.78792981e+00,  9.74498032e-03,
       -4.40596759e-01, -7.65991981e-03, -1.96067098e-01, -1.88736602e-02,
        1.13321685e-01, -3.81062363e-02,  4.03595083e-02, -3.17429261e-02,
        2.53009613e-02])

In [55]:
s0 = (1/(len(c0_x)))*np.matmul((c0_x-m0).T, (c0_x-m0))
s0

array([[ 2.49755296e+03, -5.69734936e+01,  2.94138670e+01,
        -3.39111568e+01, -1.41372553e+00,  1.34269618e+00,
         2.91755702e+00,  1.23728462e+00,  3.14040335e-01,
         2.36839770e+00, -1.35769681e+00,  9.87442695e-01,
         7.67763471e-01],
       [-5.69734936e+01,  5.03149162e+02, -2.44520629e+01,
        -4.65879340e+01, -4.35264179e+00,  8.83177914e-01,
        -2.24070451e+00, -1.86197038e+00,  2.11153445e+00,
        -5.66367041e-01, -7.36394432e-01, -2.12876922e-01,
         1.21131022e-01],
       [ 2.94138670e+01, -2.44520629e+01,  3.54310608e+02,
        -3.47031613e+00, -1.79548192e+00,  4.02895504e-01,
        -6.39344873e-01, -2.14587479e+00,  4.67591931e-01,
         5.89919229e-01,  1.16715142e+00,  7.20811176e-01,
         2.59225269e-01],
       [-3.39111568e+01, -4.65879340e+01, -3.47031613e+00,
         6.38071808e+01,  7.25432627e-01, -6.81574016e-02,
         9.93036547e-01, -8.05749813e-01,  3.01587671e-01,
        -1.87650776e-02, -1.09194280e

In [56]:
s1 = (1/(len(c1_x)))*np.matmul((c1_x-m1).T, (c1_x-m1))
s1

array([[ 3.07065125e+03, -2.20881845e+01, -3.93045458e+01,
         2.94806881e+01, -2.17453260e+00, -1.22341342e+00,
        -4.04310858e+00, -1.21855256e+00,  6.02274982e-01,
        -2.34781031e+00,  1.48878857e+00, -1.10122833e+00,
        -4.70486168e-01],
       [-2.20881845e+01,  3.73355559e+02, -1.44587380e+01,
         4.05923015e+01, -5.01379399e+00, -9.18616832e-01,
        -1.96775236e+00,  1.23812299e+00,  4.29325639e-01,
        -2.68948901e-01,  1.44355980e+00, -4.48549652e-01,
         3.99614548e-01],
       [-3.93045458e+01, -1.44587380e+01,  2.59713171e+02,
         3.04674156e+00, -1.39295335e-01, -3.78853220e-01,
        -2.00425418e-01,  1.78809843e+00,  3.08033733e-02,
        -6.58240374e-01, -8.56698654e-01, -7.47243506e-01,
        -1.27378690e-01],
       [ 2.94806881e+01,  4.05923015e+01,  3.04674156e+00,
         5.16335990e+01, -6.19801369e-01,  5.92622523e-02,
        -8.56980524e-01,  6.99088174e-01, -2.63894427e-01,
         1.70714041e-02,  9.38390797e

In [57]:
n0 = len(c0_x)
n1 = len(c1_x)

omega = np.matmul(np.linalg.inv(n0*s0 + n1*s1), (m0-m1))

In [58]:
omega

array([ 2.03264563e-05,  2.78082588e-04,  9.30131696e-05, -2.71972347e-06,
        4.69938436e-03,  1.33302212e-04,  4.65765748e-03,  5.08808679e-04,
       -5.45435737e-03,  2.89466133e-03, -3.65633199e-03,  3.13001486e-03,
       -3.40486184e-03])

In [59]:
px = np.dot(omega, x_train.T)
px

array([ 0.01247733, -0.00220505, -0.00357844, -0.01049552, -0.00602766,
        0.01755063,  0.00022571,  0.00035157,  0.02304841,  0.01259253,
       -0.00495011,  0.00430157, -0.00131482,  0.01443047, -0.0068627 ,
       -0.0134178 ,  0.02329761, -0.01183678, -0.00937939,  0.00210544,
       -0.00281418, -0.00798036, -0.01130405, -0.01259491, -0.01040654,
       -0.01193855,  0.00251147, -0.01183857, -0.00268408, -0.00896817,
       -0.00147488, -0.01830338,  0.01524795,  0.01758065, -0.01413341,
        0.017452  ,  0.01030407, -0.00341769, -0.0022792 , -0.00354456,
       -0.0065529 ,  0.01342165, -0.00098419, -0.00999663, -0.0014406 ,
        0.01913955,  0.01195973, -0.00902007, -0.00847349,  0.00699154,
       -0.01052422,  0.00866086, -0.01292683, -0.00551504,  0.01048801,
        0.01423214,  0.01067695, -0.00655258, -0.0069675 ,  0.01571174,
       -0.01303369,  0.01026098,  0.01635486, -0.01824473, -0.00723676,
       -0.01023728,  0.01442663, -0.00801773,  0.01831553, -0.00

In [60]:
px_train = [[1, i] for i in px]
px_train = np.array(px_train)
px_train

array([[ 1.00000000e+00,  1.24773345e-02],
       [ 1.00000000e+00, -2.20504894e-03],
       [ 1.00000000e+00, -3.57844062e-03],
       [ 1.00000000e+00, -1.04955161e-02],
       [ 1.00000000e+00, -6.02766019e-03],
       [ 1.00000000e+00,  1.75506313e-02],
       [ 1.00000000e+00,  2.25709420e-04],
       [ 1.00000000e+00,  3.51567947e-04],
       [ 1.00000000e+00,  2.30484138e-02],
       [ 1.00000000e+00,  1.25925342e-02],
       [ 1.00000000e+00, -4.95010721e-03],
       [ 1.00000000e+00,  4.30156560e-03],
       [ 1.00000000e+00, -1.31481655e-03],
       [ 1.00000000e+00,  1.44304705e-02],
       [ 1.00000000e+00, -6.86270433e-03],
       [ 1.00000000e+00, -1.34178016e-02],
       [ 1.00000000e+00,  2.32976121e-02],
       [ 1.00000000e+00, -1.18367787e-02],
       [ 1.00000000e+00, -9.37938564e-03],
       [ 1.00000000e+00,  2.10544125e-03],
       [ 1.00000000e+00, -2.81418467e-03],
       [ 1.00000000e+00, -7.98036317e-03],
       [ 1.00000000e+00, -1.13040512e-02],
       [ 1.

In [61]:
weight = np.zeros(2)
print(weight.reshape(-1, 1))
max_iter = 500000
learning_rate = 0.1
weight = np.zeros(2)

for _ in range(max_iter):
    p = sig(np.dot(px_train, weight))
    weight = weight - (learning_rate / (n1 + n2)) * np.matmul(px_train.T, (p - y_train))

print(weight)

[[0.]
 [0.]]
[-0.14558068 98.76582136]


In [62]:
x_test = pca.transform(x_test)
print(x_test)
x_test = np.dot(omega, x_test.T)
# px_test = [np.array([1]+list(i)) for i in x_test]
# px_test = np.array(px_test)

[[-5.13809125e+01 -2.13855619e+01 -2.33382296e+01 -4.30568227e+00
  -7.13821053e-01  5.59310439e-01  8.97070683e-01 -1.15187542e+00
   3.43495505e-01 -2.06745898e-02  6.74858831e-01  2.27348646e-01
   4.71689926e-03]
 [ 2.35770320e+00 -1.04416049e+01  5.02830487e+00  1.86953452e+00
  -1.74923882e-02 -6.22913779e-01 -1.20833290e+00 -1.50416010e+00
   2.30101925e-01  1.39001791e-01  5.01705773e-01  6.01521878e-02
  -1.42774781e-01]
 [ 4.19445022e+01 -5.71082556e+00  3.80394518e+01 -1.18908092e+00
  -4.84817882e-01 -1.10561986e+00 -3.24271152e-01  1.65755360e+00
  -4.36184349e-01  5.43659397e-01 -1.31994882e-01 -6.78303824e-01
  -4.07622433e-01]
 [-2.06002842e+01  3.88982967e+01  1.80913537e+01  3.33718830e+00
   3.79266453e-01  1.25109421e+00 -1.51783702e+00  1.20552820e+00
   1.02029771e+00  3.53204104e-01  4.93776446e-01 -5.37649856e-01
  -2.54260041e-01]
 [ 8.14616730e+00  8.01439124e+00 -1.81750066e+00  3.70870937e-01
  -3.86046758e-01 -1.06206224e+00  6.97355283e-02 -7.15942002e-01


In [63]:
x_t = [[1, i] for i in x_test]
x_t = np.array(x_t)
x_t

array([[ 1.00000000e+00, -1.25435520e-02],
       [ 1.00000000e+00, -1.09643528e-02],
       [ 1.00000000e+00,  3.41344173e-03],
       [ 1.00000000e+00,  3.99572474e-04],
       [ 1.00000000e+00, -6.94043100e-04],
       [ 1.00000000e+00,  6.02636292e-03],
       [ 1.00000000e+00, -9.56351958e-03],
       [ 1.00000000e+00, -5.17497949e-03],
       [ 1.00000000e+00,  2.00328670e-02],
       [ 1.00000000e+00, -1.42764973e-02],
       [ 1.00000000e+00, -5.59684712e-03],
       [ 1.00000000e+00,  1.96721966e-02],
       [ 1.00000000e+00,  1.01121455e-02],
       [ 1.00000000e+00,  6.44796502e-03],
       [ 1.00000000e+00,  8.53809345e-03],
       [ 1.00000000e+00,  1.57087684e-03],
       [ 1.00000000e+00, -1.04450563e-02],
       [ 1.00000000e+00,  2.20161943e-02],
       [ 1.00000000e+00, -1.22608128e-02],
       [ 1.00000000e+00, -1.12764907e-02],
       [ 1.00000000e+00, -3.92284404e-03],
       [ 1.00000000e+00,  4.55543101e-03],
       [ 1.00000000e+00,  1.22271270e-02],
       [ 1.

In [64]:
y_pred = sig(np.dot(x_t, weight))
y_final = [1 if i > 0.5 else 0 for i in y_pred]
# y_final
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test, y_final))

0.8666666666666667


In [65]:
# Random State = 2, test size = 0.1 -> 76, 83
# Random State = 10, test size = 0.2 -> 83, 73
# Random State = 42, test size = 0.2 -> 80, 74