In [1]:
import numpy as np

In [2]:
data = np.genfromtxt('Real estate.csv', delimiter=',')
data = data[1:]
print(data.shape)
print(data)

(413, 8)
[[2.0000000e+00 2.0129170e+03 1.9500000e+01 ... 2.4980340e+01
  1.2153951e+02 4.2200000e+01]
 [3.0000000e+00 2.0135830e+03 1.3300000e+01 ... 2.4987460e+01
  1.2154391e+02 4.7300000e+01]
 [4.0000000e+00 2.0135000e+03 1.3300000e+01 ... 2.4987460e+01
  1.2154391e+02 5.4800000e+01]
 ...
 [4.1200000e+02 2.0132500e+03 1.8800000e+01 ... 2.4979230e+01
  1.2153986e+02 4.0600000e+01]
 [4.1300000e+02 2.0130000e+03 8.1000000e+00 ... 2.4966740e+01
  1.2154067e+02 5.2500000e+01]
 [4.1400000e+02 2.0135000e+03 6.5000000e+00 ... 2.4974330e+01
  1.2154310e+02 6.3900000e+01]]


In [3]:
import csv

X = []
Y = []

with open('Real estate.csv', 'r') as file:
    reader = csv.reader(file)
    for row in reader:
        X.append([1.0]+[float(val) for val in row[1:-1]])
        Y.append([float(row[-1])])

print(X)
print(Y)

[[1.0, 2012.917, 32.0, 84.87882, 10.0, 24.98298, 121.54024], [1.0, 2012.917, 19.5, 306.5947, 9.0, 24.98034, 121.53951], [1.0, 2013.583, 13.3, 561.9845, 5.0, 24.98746, 121.54391], [1.0, 2013.5, 13.3, 561.9845, 5.0, 24.98746, 121.54391], [1.0, 2012.833, 5.0, 390.5684, 5.0, 24.97937, 121.54245], [1.0, 2012.667, 7.1, 2175.03, 3.0, 24.96305, 121.51254], [1.0, 2012.667, 34.5, 623.4731, 7.0, 24.97933, 121.53642], [1.0, 2013.417, 20.3, 287.6025, 6.0, 24.98042, 121.54228], [1.0, 2013.5, 31.7, 5512.038, 1.0, 24.95095, 121.48458], [1.0, 2013.417, 17.9, 1783.18, 3.0, 24.96731, 121.51486], [1.0, 2013.083, 34.8, 405.2134, 1.0, 24.97349, 121.53372], [1.0, 2013.333, 6.3, 90.45606, 9.0, 24.97433, 121.5431], [1.0, 2012.917, 13.0, 492.2313, 5.0, 24.96515, 121.53737], [1.0, 2012.667, 20.4, 2469.645, 4.0, 24.96108, 121.51046], [1.0, 2013.5, 13.2, 1164.838, 4.0, 24.99156, 121.53406], [1.0, 2013.583, 35.7, 579.2083, 2.0, 24.9824, 121.54619], [1.0, 2013.25, 0.0, 292.9978, 6.0, 24.97744, 121.54458], [1.0, 2012

In [4]:
x = np.array(X)
y = np.array(Y)

In [5]:
x

array([[1.0000000e+00, 2.0129170e+03, 3.2000000e+01, ..., 1.0000000e+01,
        2.4982980e+01, 1.2154024e+02],
       [1.0000000e+00, 2.0129170e+03, 1.9500000e+01, ..., 9.0000000e+00,
        2.4980340e+01, 1.2153951e+02],
       [1.0000000e+00, 2.0135830e+03, 1.3300000e+01, ..., 5.0000000e+00,
        2.4987460e+01, 1.2154391e+02],
       ...,
       [1.0000000e+00, 2.0132500e+03, 1.8800000e+01, ..., 7.0000000e+00,
        2.4979230e+01, 1.2153986e+02],
       [1.0000000e+00, 2.0130000e+03, 8.1000000e+00, ..., 5.0000000e+00,
        2.4966740e+01, 1.2154067e+02],
       [1.0000000e+00, 2.0135000e+03, 6.5000000e+00, ..., 9.0000000e+00,
        2.4974330e+01, 1.2154310e+02]])

In [6]:
y

array([[ 37.9],
       [ 42.2],
       [ 47.3],
       [ 54.8],
       [ 43.1],
       [ 32.1],
       [ 40.3],
       [ 46.7],
       [ 18.8],
       [ 22.1],
       [ 41.4],
       [ 58.1],
       [ 39.3],
       [ 23.8],
       [ 34.3],
       [ 50.5],
       [ 70.1],
       [ 37.4],
       [ 42.3],
       [ 47.7],
       [ 29.3],
       [ 51.6],
       [ 24.6],
       [ 47.9],
       [ 38.8],
       [ 27. ],
       [ 56.2],
       [ 33.6],
       [ 47. ],
       [ 57.1],
       [ 22.1],
       [ 25. ],
       [ 34.2],
       [ 49.3],
       [ 55.1],
       [ 27.3],
       [ 22.9],
       [ 25.3],
       [ 47.7],
       [ 46.2],
       [ 15.9],
       [ 18.2],
       [ 34.7],
       [ 34.1],
       [ 53.9],
       [ 38.3],
       [ 42. ],
       [ 61.5],
       [ 13.4],
       [ 13.2],
       [ 44.2],
       [ 20.7],
       [ 27. ],
       [ 38.9],
       [ 51.7],
       [ 13.7],
       [ 41.9],
       [ 53.5],
       [ 22.6],
       [ 42.4],
       [ 21.3],
       [ 63.2],
       [

In [7]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [8]:
theta = np.linalg.inv(x_train.T.dot(x_train)).dot(x_train.T).dot(y_train)

In [9]:
theta

array([[-1.30442328e+04],
       [ 5.44074188e+00],
       [-2.70791490e-01],
       [-4.75863885e-03],
       [ 1.09142527e+00],
       [ 2.29043056e+02],
       [-2.94925846e+01]])

In [10]:
y_pred = x_test.dot(theta)
y_pred

array([[47.88625403],
       [41.16404537],
       [44.27301416],
       [40.19761517],
       [27.51326487],
       [45.10953101],
       [44.63293261],
       [46.36346221],
       [23.62063111],
       [54.33444879],
       [34.07416438],
       [36.54533171],
       [37.55154235],
       [23.27940498],
       [35.2661415 ],
       [34.38327725],
       [43.3563349 ],
       [45.40740515],
       [30.07083136],
       [44.09191479],
       [ 0.73505967],
       [34.99271664],
       [48.2273514 ],
       [45.48646469],
       [11.59952802],
       [39.69783639],
       [12.71276232],
       [42.91282869],
       [34.93451382],
       [37.27964504],
       [13.17842168],
       [40.12708464],
       [35.21883489],
       [27.71588916],
       [46.40090918],
       [31.21941975],
       [50.90046875],
       [14.07339414],
       [49.05344261],
       [40.05384445],
       [38.24588954],
       [40.63256425],
       [47.01634742],
       [37.65598959],
       [39.85801819],
       [46

In [11]:
y_mean = y_pred.mean()
y_mean

36.216355119168206

In [12]:
tss = np.sum((y_test-y_mean).T.dot(y_test-y_mean))
tss

13925.322762898904

In [13]:
rss = np.sum((y_test-y_pred).T.dot(y_test-y_pred))
rss

4440.966384692984

In [14]:
r2 = 1 - rss/tss
r2

0.6810870052847173

In [17]:
rmse = np.sqrt(np.sum(np.square(y_test-y_pred)/(len(y_test))))
rmse

7.314753522346911