In [79]:
import numpy as np
import csv

In [80]:
X = []
Y = []

# data = []

with open('Iris.csv', 'r') as file:
    reader = csv.reader(file)
    for row in reader:
        X.append([float(val) for val in row[1:-1]])
        Y.append([row[-1]])

print(X)
print(Y)

[[5.1, 3.5, 1.4, 0.2], [4.9, 3.0, 1.4, 0.2], [4.7, 3.2, 1.3, 0.2], [4.6, 3.1, 1.5, 0.2], [5.0, 3.6, 1.4, 0.2], [5.4, 3.9, 1.7, 0.4], [4.6, 3.4, 1.4, 0.3], [5.0, 3.4, 1.5, 0.2], [4.4, 2.9, 1.4, 0.2], [4.9, 3.1, 1.5, 0.1], [5.4, 3.7, 1.5, 0.2], [4.8, 3.4, 1.6, 0.2], [4.8, 3.0, 1.4, 0.1], [4.3, 3.0, 1.1, 0.1], [5.8, 4.0, 1.2, 0.2], [5.7, 4.4, 1.5, 0.4], [5.4, 3.9, 1.3, 0.4], [5.1, 3.5, 1.4, 0.3], [5.7, 3.8, 1.7, 0.3], [5.1, 3.8, 1.5, 0.3], [5.4, 3.4, 1.7, 0.2], [5.1, 3.7, 1.5, 0.4], [4.6, 3.6, 1.0, 0.2], [5.1, 3.3, 1.7, 0.5], [4.8, 3.4, 1.9, 0.2], [5.0, 3.0, 1.6, 0.2], [5.0, 3.4, 1.6, 0.4], [5.2, 3.5, 1.5, 0.2], [5.2, 3.4, 1.4, 0.2], [4.7, 3.2, 1.6, 0.2], [4.8, 3.1, 1.6, 0.2], [5.4, 3.4, 1.5, 0.4], [5.2, 4.1, 1.5, 0.1], [5.5, 4.2, 1.4, 0.2], [4.9, 3.1, 1.5, 0.1], [5.0, 3.2, 1.2, 0.2], [5.5, 3.5, 1.3, 0.2], [4.9, 3.1, 1.5, 0.1], [4.4, 3.0, 1.3, 0.2], [5.1, 3.4, 1.5, 0.2], [5.0, 3.5, 1.3, 0.3], [4.5, 2.3, 1.3, 0.3], [4.4, 3.2, 1.3, 0.2], [5.0, 3.5, 1.6, 0.6], [5.1, 3.8, 1.9, 0.4], [4.8, 3.0

In [81]:
X = np.array(X)
Y = np.array(Y)

In [82]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=3)

In [83]:
x_train

array([[5.8, 4. , 1.2, 0.2],
       [4.8, 3.4, 1.9, 0.2],
       [6.9, 3.1, 5.4, 2.1],
       [6.6, 2.9, 4.6, 1.3],
       [4.4, 2.9, 1.4, 0.2],
       [5.2, 3.5, 1.5, 0.2],
       [6.7, 3. , 5. , 1.7],
       [4.5, 2.3, 1.3, 0.3],
       [6.4, 2.7, 5.3, 1.9],
       [6.2, 2.2, 4.5, 1.5],
       [6.4, 2.8, 5.6, 2.1],
       [5.8, 2.7, 3.9, 1.2],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.5, 1.4, 0.3],
       [6.1, 3. , 4.9, 1.8],
       [6.4, 3.2, 4.5, 1.5],
       [5.1, 3.3, 1.7, 0.5],
       [6. , 2.7, 5.1, 1.6],
       [5.8, 2.7, 5.1, 1.9],
       [5.4, 3. , 4.5, 1.5],
       [4.8, 3. , 1.4, 0.3],
       [5. , 3.2, 1.2, 0.2],
       [5.8, 2.7, 5.1, 1.9],
       [7. , 3.2, 4.7, 1.4],
       [6.1, 2.8, 4.7, 1.2],
       [4.9, 3.1, 1.5, 0.1],
       [6.3, 3.4, 5.6, 2.4],
       [5.1, 3.8, 1.5, 0.3],
       [6.5, 3. , 5.5, 1.8],
       [5.7, 2.9, 4.2, 1.3],
       [5. , 3.6, 1.4, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [6.8, 3.2, 5.9, 2.3],
       [5.9, 3.2, 4.8, 1.8],
       [5.4, 3

In [84]:
y_train

array([['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-virginica'],
       ['Iris-versicolor'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-versicolor'],
       ['Iris-setosa'],
       ['Iris-virginica'],
       ['Iris-versicolor'],
       ['Iris-virginica'],
       ['Iris-versicolor'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-virginica'],
       ['Iris-versicolor'],
       ['Iris-setosa'],
       ['Iris-versicolor'],
       ['Iris-virginica'],
       ['Iris-versicolor'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-virginica'],
       ['Iris-versicolor'],
       ['Iris-versicolor'],
       ['Iris-setosa'],
       ['Iris-virginica'],
       ['Iris-setosa'],
       ['Iris-virginica'],
       ['Iris-versicolor'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-virginica'],
       ['Iris-versicolor'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-versicolor'],
       ['Iris-virginica'],
       ['I

In [85]:
clusters = {1:[], 2:[], 3:[]}
c1 = []
c2 = []
c3 = []
for i in range(len(x_train)):
    if y_train[i][0] == 'Iris-setosa':
        clusters[1].append(i)
        c1.append(x_train[i])
    elif y_train[i][0] == 'Iris-versicolor':
        clusters[2].append(i)
        c2.append(x_train[i])
    elif y_train[i][0] == 'Iris-virginica':
        clusters[3].append(i)
        c3.append(x_train[i])

c1 = np.array(c1)
c2 = np.array(c2)
c3 = np.array(c3)
clusters

{1: [0,
  1,
  4,
  5,
  7,
  12,
  13,
  16,
  20,
  21,
  25,
  27,
  30,
  31,
  34,
  35,
  39,
  42,
  43,
  50,
  51,
  58,
  60,
  65,
  67,
  71,
  73,
  80,
  85,
  88,
  90,
  91,
  92,
  95,
  96,
  98,
  108,
  111,
  116,
  117],
 2: [3,
  6,
  9,
  11,
  15,
  17,
  19,
  23,
  24,
  29,
  33,
  36,
  41,
  47,
  48,
  49,
  54,
  56,
  61,
  62,
  66,
  68,
  69,
  70,
  75,
  77,
  79,
  82,
  84,
  86,
  89,
  93,
  99,
  101,
  104,
  105,
  107,
  109,
  110,
  112],
 3: [2,
  8,
  10,
  14,
  18,
  22,
  26,
  28,
  32,
  37,
  38,
  40,
  44,
  45,
  46,
  52,
  53,
  55,
  57,
  59,
  63,
  64,
  72,
  74,
  76,
  78,
  81,
  83,
  87,
  94,
  97,
  100,
  102,
  103,
  106,
  113,
  114,
  115,
  118,
  119]}

In [86]:
c1

array([[5.8, 4. , 1.2, 0.2],
       [4.8, 3.4, 1.9, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [5.2, 3.5, 1.5, 0.2],
       [4.5, 2.3, 1.3, 0.3],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.5, 1.4, 0.3],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3. , 1.4, 0.3],
       [5. , 3.2, 1.2, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.1, 3.8, 1.5, 0.3],
       [5. , 3.6, 1.4, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [4.7, 3.2, 1.6, 0.2],
       [5.1, 3.4, 1.5, 0.2],
       [5.1, 3.8, 1.9, 0.4],
       [5.5, 3.5, 1.3, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [4.3, 3. , 1.1, 0.1],
       [5.2, 4.1, 1.5, 0.1],
       [5.4, 3.9, 1.3, 0.4],
       [4.9, 3. , 1.4, 0.2],
       [5.1, 3.8, 1.6, 0.2],
       [5.7, 3.8, 1.7, 0.3],
       [5.2, 3.4, 1.4, 0.2],
       [5. , 3.3, 1.4, 0.2],
       [5.4, 3.4, 1.7, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.3, 3.7, 1.5, 0.2],
       [5.5, 4.2, 1.4, 0.2],
       [5. , 3

In [87]:
m1 = np.mean(c1, axis=0)
m1

array([5.03  , 3.42  , 1.4675, 0.235 ])

In [88]:
c2

array([[6.6, 2.9, 4.6, 1.3],
       [6.7, 3. , 5. , 1.7],
       [6.2, 2.2, 4.5, 1.5],
       [5.8, 2.7, 3.9, 1.2],
       [6.4, 3.2, 4.5, 1.5],
       [6. , 2.7, 5.1, 1.6],
       [5.4, 3. , 4.5, 1.5],
       [7. , 3.2, 4.7, 1.4],
       [6.1, 2.8, 4.7, 1.2],
       [5.7, 2.9, 4.2, 1.3],
       [5.9, 3.2, 4.8, 1.8],
       [5.1, 2.5, 3. , 1.1],
       [5.7, 3. , 4.2, 1.2],
       [5.7, 2.8, 4.1, 1.3],
       [5.2, 2.7, 3.9, 1.4],
       [6.3, 2.3, 4.4, 1.3],
       [6.9, 3.1, 4.9, 1.5],
       [5.9, 3. , 4.2, 1.5],
       [5.7, 2.8, 4.5, 1.3],
       [6.6, 3. , 4.4, 1.4],
       [5.5, 2.4, 3.8, 1.1],
       [6.1, 3. , 4.6, 1.4],
       [6.4, 2.9, 4.3, 1.3],
       [6. , 3.4, 4.5, 1.6],
       [6.1, 2.8, 4. , 1.3],
       [6.3, 3.3, 4.7, 1.6],
       [6.1, 2.9, 4.7, 1.4],
       [5.6, 2.9, 3.6, 1.3],
       [6.5, 2.8, 4.6, 1.5],
       [6. , 2.9, 4.5, 1.5],
       [5.6, 2.7, 4.2, 1.3],
       [5.7, 2.6, 3.5, 1. ],
       [6. , 2.2, 4. , 1. ],
       [6.2, 2.9, 4.3, 1.3],
       [5.6, 2

In [89]:
m2 = np.mean(c2, axis=0)
m2

array([5.93  , 2.7875, 4.2675, 1.335 ])

In [90]:
c3

array([[6.9, 3.1, 5.4, 2.1],
       [6.4, 2.7, 5.3, 1.9],
       [6.4, 2.8, 5.6, 2.1],
       [6.1, 3. , 4.9, 1.8],
       [5.8, 2.7, 5.1, 1.9],
       [5.8, 2.7, 5.1, 1.9],
       [6.3, 3.4, 5.6, 2.4],
       [6.5, 3. , 5.5, 1.8],
       [6.8, 3.2, 5.9, 2.3],
       [6.4, 3.1, 5.5, 1.8],
       [6.3, 3.3, 6. , 2.5],
       [6.7, 3.3, 5.7, 2.1],
       [7.4, 2.8, 6.1, 1.9],
       [7.7, 3.8, 6.7, 2.2],
       [5.8, 2.8, 5.1, 2.4],
       [6.4, 3.2, 5.3, 2.3],
       [6.7, 3.3, 5.7, 2.5],
       [7.1, 3. , 5.9, 2.1],
       [7.7, 2.8, 6.7, 2. ],
       [6.3, 2.8, 5.1, 1.5],
       [6.4, 2.8, 5.6, 2.2],
       [6.2, 3.4, 5.4, 2.3],
       [7.2, 3.2, 6. , 1.8],
       [6.7, 2.5, 5.8, 1.8],
       [6.7, 3. , 5.2, 2.3],
       [5.6, 2.8, 4.9, 2. ],
       [7.6, 3. , 6.6, 2.1],
       [6.5, 3. , 5.2, 2. ],
       [6.3, 2.5, 5. , 1.9],
       [6.3, 2.7, 4.9, 1.8],
       [6.9, 3.2, 5.7, 2.3],
       [5.9, 3. , 5.1, 1.8],
       [6.5, 3.2, 5.1, 2. ],
       [6.5, 3. , 5.8, 2.2],
       [7.2, 3

In [91]:
m3 = np.mean(c3, axis=0)
m3

array([6.5525, 2.9875, 5.5325, 2.01  ])

In [92]:
(c1[0]-m1).reshape(4,1)

array([[ 0.77  ],
       [ 0.58  ],
       [-0.2675],
       [-0.035 ]])

In [93]:
c1[0]-m1

array([ 0.77  ,  0.58  , -0.2675, -0.035 ])

In [94]:
sj1 = np.zeros((4,4))
for i in c1:
    sj1 += np.matmul((i-m1).reshape(4,1), (i-m1).reshape(1,4))
sj1

array([[4.044  , 3.436  , 0.419  , 0.228  ],
       [3.436  , 5.364  , 0.386  , 0.262  ],
       [0.419  , 0.386  , 1.30775, 0.2355 ],
       [0.228  , 0.262  , 0.2355 , 0.471  ]])

In [95]:
sj2 = np.zeros((4,4))
for i in c2:
    sj2 += np.matmul((i-m2).reshape(4,1), (i-m2).reshape(1,4))
sj2

array([[9.404  , 3.085  , 6.489  , 1.988  ],
       [3.085  , 4.00375, 3.44375, 1.7975 ],
       [6.489  , 3.44375, 8.72775, 2.9255 ],
       [1.988  , 1.7975 , 2.9255 , 1.611  ]])

In [96]:
sj3 = np.zeros((4,4))
for i in c3:
    sj3 += np.matmul((i-m3).reshape(4,1), (i-m3).reshape(1,4))
sj3

array([[15.49975,  3.86625, 11.79175,  0.859  ],
       [ 3.86625,  4.12375,  3.33625,  1.755  ],
       [11.79175,  3.33625, 11.40775,  1.567  ],
       [ 0.859  ,  1.755  ,  1.567  ,  2.596  ]])

In [97]:
sw = sj1+sj2+sj3

In [98]:
sw

array([[28.94775, 10.38725, 18.69975,  3.075  ],
       [10.38725, 13.4915 ,  7.166  ,  3.8145 ],
       [18.69975,  7.166  , 21.44325,  4.728  ],
       [ 3.075  ,  3.8145 ,  4.728  ,  4.678  ]])

In [99]:
m = (m1+m2+m3)/3
m

array([5.8375    , 3.065     , 3.75583333, 1.19333333])

In [100]:
sb1 = len(c1)*np.matmul((m1-m).reshape(4,1), (m1-m).reshape(1,4))
sb1

array([[ 26.08225   , -11.4665    ,  73.91316667,  30.95416667],
       [-11.4665    ,   5.041     , -32.49433333, -13.60833333],
       [ 73.91316667, -32.49433333, 209.45877778,  87.71944444],
       [ 30.95416667, -13.60833333,  87.71944444,  36.73611111]])

In [101]:
sb2 = len(c2)*np.matmul((m2-m).reshape(4,1), (m2-m).reshape(1,4))
sb2

array([[ 0.34225   , -1.02675   ,  1.89316667,  0.52416667],
       [-1.02675   ,  3.08025   , -5.6795    , -1.5725    ],
       [ 1.89316667, -5.6795    , 10.47211111,  2.89944444],
       [ 0.52416667, -1.5725    ,  2.89944444,  0.80277778]])

In [102]:
sb3 = len(c3)*np.matmul((m3-m).reshape(4,1), (m3-m).reshape(1,4))
sb3

array([[ 20.449     ,  -2.2165    ,  50.81266667,  23.35666667],
       [ -2.2165    ,   0.24025   ,  -5.50766667,  -2.53166667],
       [ 50.81266667,  -5.50766667, 126.26177778,  58.03777778],
       [ 23.35666667,  -2.53166667,  58.03777778,  26.67777778]])

In [103]:
sb = sb1+sb2+sb3
sb

array([[ 46.8735    , -14.70975   , 126.619     ,  54.835     ],
       [-14.70975   ,   8.3615    , -43.6815    , -17.7125    ],
       [126.619     , -43.6815    , 346.19266667, 148.65666667],
       [ 54.835     , -17.7125    , 148.65666667,  64.21666667]])

In [104]:
sw_inv_sb = np.matmul(np.linalg.inv(sw), sb)
sw_inv_sb

array([[ -1.96297753,   0.73284402,  -5.42566661,  -2.31212083],
       [ -6.60059822,   2.51161888, -18.29398304,  -7.78098991],
       [  7.42030166,  -2.73160329,  20.46899001,   8.73490464],
       [ 10.8948165 ,  -3.55526833,  29.57366504,  12.76365864]])

In [105]:
eigenval, eigenvec = np.linalg.eig(sw_inv_sb)

In [106]:
eigenval

array([3.35160251e+01, 2.65264869e-01, 3.46175630e-15, 1.14884274e-15])

In [107]:
eigenvec

array([[ 0.13356863, -0.11180594, -0.24904972, -0.47320857],
       [ 0.45065621, -0.50689157,  0.38780245,  0.42943656],
       [-0.50366235,  0.3158995 ,  0.46468377,  0.48397844],
       [-0.72483973, -0.79420896, -0.75607704, -0.59784844]])

In [108]:
largest_eigenvec = eigenvec[np.argsort(eigenval)[-1]]
largest_eigenvec

array([ 0.13356863, -0.11180594, -0.24904972, -0.47320857])

In [109]:
projected_data = x_train.dot(largest_eigenvec.T)
# projected_data.shape


train_data = [i for i in projected_data]#list(zip(projected_data, y_train))
classes = [j[0] for j in y_train]
classes

['Iris-setosa',
 'Iris-setosa',
 'Iris-virginica',
 'Iris-versicolor',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-versicolor',
 'Iris-setosa',
 'Iris-virginica',
 'Iris-versicolor',
 'Iris-virginica',
 'Iris-versicolor',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-virginica',
 'Iris-versicolor',
 'Iris-setosa',
 'Iris-versicolor',
 'Iris-virginica',
 'Iris-versicolor',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-virginica',
 'Iris-versicolor',
 'Iris-versicolor',
 'Iris-setosa',
 'Iris-virginica',
 'Iris-setosa',
 'Iris-virginica',
 'Iris-versicolor',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-virginica',
 'Iris-versicolor',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-versicolor',
 'Iris-virginica',
 'Iris-virginica',
 'Iris-setosa',
 'Iris-virginica',
 'Iris-versicolor',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-virginica',
 'Iris-virginica',
 'Iris-virginica',
 'Iris-versicolor',
 'Iris-versicolor',
 'Iris-versicolor',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-virginica',
 'Iris-virginica',
 'Iris-versicolor',
 

In [110]:
train_data = np.array(train_data).reshape(-1,1)
train_data

array([[-0.06602709],
       [-0.30684696],
       [-1.76358137],
       [-1.20348413],
       [-0.17984658],
       [-0.16498021],
       [-1.49021118],
       [-0.12182204],
       [-1.66609662],
       [-1.24838417],
       [-1.84663384],
       [-1.06632219],
       [-0.13177712],
       [-0.20075296],
       [-1.59276824],
       [-1.33347638],
       [-0.3477484 ],
       [-1.52775155],
       [-1.69642785],
       [-1.44468382],
       [-0.18492058],
       [-0.08343724],
       [-1.69642785],
       [-1.25582429],
       [-1.23667197],
       [-0.11300757],
       [-2.06903684],
       [-0.25919971],
       [-1.68877062],
       [-1.22407601],
       [-0.17796956],
       [-0.09027886],
       [-2.0072854 ],
       [-1.61693819],
       [-0.16062767],
       [-0.23213204],
       [-0.86599343],
       [-1.71330808],
       [-2.20479699],
       [-0.11300757],
       [-1.8873712 ],
       [-1.18793575],
       [-0.22312772],
       [-0.16715648],
       [-1.74294836],
       [-2

In [111]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(train_data, classes)

KNeighborsClassifier()

In [112]:
projected_data_test = x_test.dot(largest_eigenvec.T)
projected_data_test = projected_data_test.reshape(-1,1)
projected_data_test

array([[-0.18667464],
       [-0.20039901],
       [-0.22172761],
       [-0.16069594],
       [-0.29346296],
       [-2.06903979],
       [-1.15625742],
       [-0.25635668],
       [-1.72920873],
       [-1.20999937],
       [-1.22370849],
       [-0.1661222 ],
       [-1.08004656],
       [-1.13389623],
       [-1.98206761],
       [-0.18920485],
       [-1.36818898],
       [-1.91452239],
       [-1.70983941],
       [-0.18848339],
       [-1.53214522],
       [-1.79066261],
       [-1.78350817],
       [-1.26272061],
       [-0.32744052],
       [-2.14303198],
       [-1.53309724],
       [-1.02149041],
       [-0.90892062],
       [-1.33203514]])

In [113]:
predicted_data = knn.predict(projected_data_test)
predicted_data

array(['Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-virginica', 'Iris-versicolor', 'Iris-setosa',
       'Iris-virginica', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-setosa', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-virginica', 'Iris-setosa', 'Iris-versicolor',
       'Iris-virginica', 'Iris-virginica', 'Iris-setosa',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
       'Iris-versicolor', 'Iris-setosa', 'Iris-virginica',
       'Iris-virginica', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor'], dtype='<U15')

In [114]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test, predicted_data))

1.0


In [115]:
knn2 = KNeighborsClassifier(n_neighbors=5)
knn.fit(x_train, y_train.reshape(1,-1)[0])

KNeighborsClassifier()

In [116]:
predicted_data2 = knn.predict(x_test)
predicted_data2

array(['Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-virginica', 'Iris-versicolor', 'Iris-setosa',
       'Iris-virginica', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-setosa', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-virginica', 'Iris-setosa', 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica', 'Iris-setosa',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
       'Iris-versicolor', 'Iris-setosa', 'Iris-virginica',
       'Iris-virginica', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor'], dtype='<U15')

In [117]:
print(accuracy_score(y_test, predicted_data2))

0.9666666666666667
