In [476]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

In [477]:
df = pd.read_csv('Iris_Q5.csv')
df['Species'] = df['Species'].map({'Iris-setosa':1, 'Iris-versicolor':2, 'Iris-virginica':3})

In [478]:
df

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0      1            5.1           3.5            1.4           0.2        1
1      2            4.9           3.0            1.4           0.2        1
2      3            4.7           3.2            1.3           0.2        1
3      4            4.6           3.1            1.5           0.2        1
4      5            5.0           3.6            1.4           0.2        1
..   ...            ...           ...            ...           ...      ...
145  146            6.7           3.0            5.2           2.3        3
146  147            6.3           2.5            5.0           1.9        3
147  148            6.5           3.0            5.2           2.0        3
148  149            6.2           3.4            5.4           2.3        3
149  150            5.9           3.0            5.1           1.8        3

[150 rows x 6 columns]

In [479]:
c1 = df[df.Species == 1]
x1 = c1.drop(columns=['Id', 'Species']).to_numpy()
y1 = c1['Species'].to_numpy()

In [480]:
x1

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [481]:
y1

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1])

In [482]:
x1_train, x1_test, y1_train, y1_test = train_test_split(x1, y1, test_size=0.2, random_state=53)

In [483]:
x1_train

array([[5. , 3.4, 1.5, 0.2],
       [5.1, 3.8, 1.5, 0.3],
       [4.3, 3. , 1.1, 0.1],
       [4.4, 3. , 1.3, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [4.4, 3.2, 1.3, 0.2],
       [5.1, 3.5, 1.4, 0.2],
       [5. , 3.5, 1.3, 0.3],
       [5.3, 3.7, 1.5, 0.2],
       [4.8, 3. , 1.4, 0.3],
       [5.7, 4.4, 1.5, 0.4],
       [4.5, 2.3, 1.3, 0.3],
       [5.4, 3.7, 1.5, 0.2],
       [5.1, 3.8, 1.6, 0.2],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.8, 1.9, 0.4],
       [5.8, 4. , 1.2, 0.2],
       [4.6, 3.4, 1.4, 0.3],
       [5.1, 3.4, 1.5, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [4.6, 3.2, 1.4, 0.2],
       [5.5, 3.5, 1.3, 0.2],
       [5. , 3.5, 1.6, 0.6],
       [5.2, 3.5, 1.5, 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [5. , 3.4, 1.6, 0.4],
       [5. , 3.2, 1.2, 0.2],
       [5.4, 3.4, 1.7, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [5. , 3.3, 1.4, 0.2],
       [5.7, 3.8, 1.7, 0.3],
       [5.4, 3.9, 1.7, 0.4],
       [4.9, 3.1, 1.5, 0.1],
       [4.8, 3

In [484]:
c2 = df[df.Species == 2]
x2 = c2.drop(columns=['Id', 'Species']).to_numpy()
y2 = c2['Species'].to_numpy()

In [485]:
x2

array([[7. , 3.2, 4.7, 1.4],
       [6.4, 3.2, 4.5, 1.5],
       [6.9, 3.1, 4.9, 1.5],
       [5.5, 2.3, 4. , 1.3],
       [6.5, 2.8, 4.6, 1.5],
       [5.7, 2.8, 4.5, 1.3],
       [6.3, 3.3, 4.7, 1.6],
       [4.9, 2.4, 3.3, 1. ],
       [6.6, 2.9, 4.6, 1.3],
       [5.2, 2.7, 3.9, 1.4],
       [5. , 2. , 3.5, 1. ],
       [5.9, 3. , 4.2, 1.5],
       [6. , 2.2, 4. , 1. ],
       [6.1, 2.9, 4.7, 1.4],
       [5.6, 2.9, 3.6, 1.3],
       [6.7, 3.1, 4.4, 1.4],
       [5.6, 3. , 4.5, 1.5],
       [5.8, 2.7, 4.1, 1. ],
       [6.2, 2.2, 4.5, 1.5],
       [5.6, 2.5, 3.9, 1.1],
       [5.9, 3.2, 4.8, 1.8],
       [6.1, 2.8, 4. , 1.3],
       [6.3, 2.5, 4.9, 1.5],
       [6.1, 2.8, 4.7, 1.2],
       [6.4, 2.9, 4.3, 1.3],
       [6.6, 3. , 4.4, 1.4],
       [6.8, 2.8, 4.8, 1.4],
       [6.7, 3. , 5. , 1.7],
       [6. , 2.9, 4.5, 1.5],
       [5.7, 2.6, 3.5, 1. ],
       [5.5, 2.4, 3.8, 1.1],
       [5.5, 2.4, 3.7, 1. ],
       [5.8, 2.7, 3.9, 1.2],
       [6. , 2.7, 5.1, 1.6],
       [5.4, 3

In [486]:
y2

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2])

In [487]:
x2_train, x2_test, y2_train, y2_test = train_test_split(x2, y2, test_size=0.2, random_state=42)

In [488]:
c3 = df[df.Species == 3]
x3 = c3.drop(columns=['Id', 'Species']).to_numpy()
y3 = c3['Species'].to_numpy()

In [489]:
x3

array([[6.3, 3.3, 6. , 2.5],
       [5.8, 2.7, 5.1, 1.9],
       [7.1, 3. , 5.9, 2.1],
       [6.3, 2.9, 5.6, 1.8],
       [6.5, 3. , 5.8, 2.2],
       [7.6, 3. , 6.6, 2.1],
       [4.9, 2.5, 4.5, 1.7],
       [7.3, 2.9, 6.3, 1.8],
       [6.7, 2.5, 5.8, 1.8],
       [7.2, 3.6, 6.1, 2.5],
       [6.5, 3.2, 5.1, 2. ],
       [6.4, 2.7, 5.3, 1.9],
       [6.8, 3. , 5.5, 2.1],
       [5.7, 2.5, 5. , 2. ],
       [5.8, 2.8, 5.1, 2.4],
       [6.4, 3.2, 5.3, 2.3],
       [6.5, 3. , 5.5, 1.8],
       [7.7, 3.8, 6.7, 2.2],
       [7.7, 2.6, 6.9, 2.3],
       [6. , 2.2, 5. , 1.5],
       [6.9, 3.2, 5.7, 2.3],
       [5.6, 2.8, 4.9, 2. ],
       [7.7, 2.8, 6.7, 2. ],
       [6.3, 2.7, 4.9, 1.8],
       [6.7, 3.3, 5.7, 2.1],
       [7.2, 3.2, 6. , 1.8],
       [6.2, 2.8, 4.8, 1.8],
       [6.1, 3. , 4.9, 1.8],
       [6.4, 2.8, 5.6, 2.1],
       [7.2, 3. , 5.8, 1.6],
       [7.4, 2.8, 6.1, 1.9],
       [7.9, 3.8, 6.4, 2. ],
       [6.4, 2.8, 5.6, 2.2],
       [6.3, 2.8, 5.1, 1.5],
       [6.1, 2

In [490]:
y3

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3])

In [491]:
x3_train, x3_test, y3_train, y3_test = train_test_split(x3, y3, test_size=0.2, random_state=42)

In [492]:
def sig(x):
    return 1/(1+np.exp(-x))

In [493]:
fx1 = []
fy1 = []
for i in x1_train:
    fx1.append(i)
    fy1.append(1)

for i in x2_train:
    fx1.append(i)
    fy1.append(0)

for i in x3_train:
    fx1.append(i)
    fy1.append(0)

fx1 = np.array(fx1)
fy1 = np.array(fy1)

In [494]:
print(fx1)

[[5.  3.4 1.5 0.2]
 [5.1 3.8 1.5 0.3]
 [4.3 3.  1.1 0.1]
 [4.4 3.  1.3 0.2]
 [5.4 3.4 1.5 0.4]
 [4.4 3.2 1.3 0.2]
 [5.1 3.5 1.4 0.2]
 [5.  3.5 1.3 0.3]
 [5.3 3.7 1.5 0.2]
 [4.8 3.  1.4 0.3]
 [5.7 4.4 1.5 0.4]
 [4.5 2.3 1.3 0.3]
 [5.4 3.7 1.5 0.2]
 [5.1 3.8 1.6 0.2]
 [5.4 3.9 1.3 0.4]
 [5.1 3.8 1.9 0.4]
 [5.8 4.  1.2 0.2]
 [4.6 3.4 1.4 0.3]
 [5.1 3.4 1.5 0.2]
 [4.6 3.1 1.5 0.2]
 [4.8 3.1 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.5 3.5 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.2 3.5 1.5 0.2]
 [5.1 3.3 1.7 0.5]
 [5.  3.4 1.6 0.4]
 [5.  3.2 1.2 0.2]
 [5.4 3.4 1.7 0.2]
 [4.8 3.4 1.6 0.2]
 [5.  3.3 1.4 0.2]
 [5.7 3.8 1.7 0.3]
 [5.4 3.9 1.7 0.4]
 [4.9 3.1 1.5 0.1]
 [4.8 3.  1.4 0.1]
 [4.8 3.4 1.9 0.2]
 [4.6 3.6 1.  0.2]
 [4.9 3.1 1.5 0.1]
 [4.7 3.2 1.6 0.2]
 [5.  3.  1.6 0.2]
 [6.  2.2 4.  1. ]
 [6.5 2.8 4.6 1.5]
 [6.3 2.3 4.4 1.3]
 [6.6 2.9 4.6 1.3]
 [5.5 2.3 4.  1.3]
 [6.3 3.3 4.7 1.6]
 [6.1 3.  4.6 1.4]
 [5.7 2.9 4.2 1.3]
 [6.2 2.9 4.3 1.3]
 [6.7 3.1 4.4 1.4]
 [5.2 2.7 3.9 1.4]
 [5.6 3.  4.5 1.5]
 [6.4 2.9 4.

In [495]:
# print(fy1)
fy1 = fy1.reshape(-1,1)
print(fy1.shape)

(120, 1)


In [496]:
weight_1 = np.zeros(4)
weight_1 = weight_1.reshape(-1, 1)
max_iter = 500000
learning_rate = 0.1
n1 = len(x1_train)
n2 = len(x2_train) + len(x3_train)

for _ in range(max_iter):
    p = sig(np.dot(fx1, weight_1))
    p = p.reshape(-1,1)
    weight_1 = weight_1 - (learning_rate / (n1 + n2)) * np.matmul(fx1.T, (p - fy1))

print(weight_1)

[[ 1.61855053]
 [ 4.56487386]
 [-7.2970188 ]
 [-3.30035124]]


In [497]:
fx2 = []
fy2 = []
for i in x1_train:
    fx2.append(i)
    fy2.append(0)

for i in x2_train:
    fx2.append(i)
    fy2.append(1)

for i in x3_train:
    fx2.append(i)
    fy2.append(0)

fx2 = np.array(fx2)
fy2 = np.array(fy2)

In [498]:
fx2

array([[5. , 3.4, 1.5, 0.2],
       [5.1, 3.8, 1.5, 0.3],
       [4.3, 3. , 1.1, 0.1],
       [4.4, 3. , 1.3, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [4.4, 3.2, 1.3, 0.2],
       [5.1, 3.5, 1.4, 0.2],
       [5. , 3.5, 1.3, 0.3],
       [5.3, 3.7, 1.5, 0.2],
       [4.8, 3. , 1.4, 0.3],
       [5.7, 4.4, 1.5, 0.4],
       [4.5, 2.3, 1.3, 0.3],
       [5.4, 3.7, 1.5, 0.2],
       [5.1, 3.8, 1.6, 0.2],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.8, 1.9, 0.4],
       [5.8, 4. , 1.2, 0.2],
       [4.6, 3.4, 1.4, 0.3],
       [5.1, 3.4, 1.5, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [4.6, 3.2, 1.4, 0.2],
       [5.5, 3.5, 1.3, 0.2],
       [5. , 3.5, 1.6, 0.6],
       [5.2, 3.5, 1.5, 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [5. , 3.4, 1.6, 0.4],
       [5. , 3.2, 1.2, 0.2],
       [5.4, 3.4, 1.7, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [5. , 3.3, 1.4, 0.2],
       [5.7, 3.8, 1.7, 0.3],
       [5.4, 3.9, 1.7, 0.4],
       [4.9, 3.1, 1.5, 0.1],
       [4.8, 3

In [499]:
fy2 = fy2.reshape(-1,1)
print(fy2)

[[0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]]


In [500]:
weight_2 = np.zeros(4)
weight_2 = weight_2.reshape(-1, 1)
max_iter = 500000
learning_rate = 0.1
n1 = len(x2)
n2 = len(x1) + len(x3)

for _ in range(max_iter):
    p = sig(np.dot(fx2, weight_2))
    p = p.reshape(-1,1)
    weight_2 = weight_2 - (learning_rate / (n1 + n2)) * np.matmul(fx2.T, (p - fy2))

print(weight_2)

[[ 0.61123943]
 [-1.70869902]
 [ 1.04145211]
 [-2.63482071]]


In [501]:
fx3 = []
fy3 = []
for i in x1_train:
    fx3.append(i)
    fy3.append(0)

for i in x2_train:
    fx3.append(i)
    fy3.append(0)

for i in x3_train:
    fx3.append(i)
    fy3.append(1)

fx3 = np.array(fx3)
fy3 = np.array(fy3)

# x_train3, x_test3, y_train3, y_test3 = train_test_split(fx3, fy3, test_size=0.1, random_state=42)

In [502]:
fx3

array([[5. , 3.4, 1.5, 0.2],
       [5.1, 3.8, 1.5, 0.3],
       [4.3, 3. , 1.1, 0.1],
       [4.4, 3. , 1.3, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [4.4, 3.2, 1.3, 0.2],
       [5.1, 3.5, 1.4, 0.2],
       [5. , 3.5, 1.3, 0.3],
       [5.3, 3.7, 1.5, 0.2],
       [4.8, 3. , 1.4, 0.3],
       [5.7, 4.4, 1.5, 0.4],
       [4.5, 2.3, 1.3, 0.3],
       [5.4, 3.7, 1.5, 0.2],
       [5.1, 3.8, 1.6, 0.2],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.8, 1.9, 0.4],
       [5.8, 4. , 1.2, 0.2],
       [4.6, 3.4, 1.4, 0.3],
       [5.1, 3.4, 1.5, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [4.6, 3.2, 1.4, 0.2],
       [5.5, 3.5, 1.3, 0.2],
       [5. , 3.5, 1.6, 0.6],
       [5.2, 3.5, 1.5, 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [5. , 3.4, 1.6, 0.4],
       [5. , 3.2, 1.2, 0.2],
       [5.4, 3.4, 1.7, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [5. , 3.3, 1.4, 0.2],
       [5.7, 3.8, 1.7, 0.3],
       [5.4, 3.9, 1.7, 0.4],
       [4.9, 3.1, 1.5, 0.1],
       [4.8, 3

In [503]:
fy3 = fy3.reshape(-1,1)
print(fy3)

[[0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]]


In [504]:
weight_3 = np.zeros(4)
weight_3 = weight_3.reshape(-1, 1)
max_iter = 500000
learning_rate = 0.1
n1 = len(x3)
n2 = len(x1) + len(x1)

for _ in range(max_iter):
    p = sig(np.dot(fx3, weight_3))
    p = p.reshape(-1,1)
    weight_3 = weight_3 - (learning_rate / (n1 + n2)) * np.matmul(fx3.T, (p - fy3))

print(weight_3)

[[-5.92725331]
 [-6.01029786]
 [ 7.85626809]
 [ 9.36825809]]


In [505]:
x_test = np.concatenate((x1_test, x2_test, x3_test))
y_test = np.concatenate((y1_test, y2_test, y3_test))

In [506]:
x_test

array([[4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.4, 2.9, 1.4, 0.2],
       [5.1, 3.5, 1.4, 0.3],
       [5.2, 4.1, 1.5, 0.1],
       [5. , 3.6, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [6.1, 2.9, 4.7, 1.4],
       [5.5, 2.5, 4. , 1.3],
       [5.5, 2.4, 3.8, 1.1],
       [5.7, 3. , 4.2, 1.2],
       [5.8, 2.7, 4.1, 1. ],
       [5.1, 2.5, 3. , 1.1],
       [6.8, 2.8, 4.8, 1.4],
       [6.6, 3. , 4.4, 1.4],
       [5.8, 2.7, 3.9, 1.2],
       [5.6, 2.5, 3.9, 1.1],
       [5.7, 2.5, 5. , 2. ],
       [6.9, 3.1, 5.4, 2.1],
       [7.4, 2.8, 6.1, 1.9],
       [6.7, 3. , 5.2, 2.3],
       [7.7, 3.8, 6.7, 2.2],
       [6.2, 3.4, 5.4, 2.3],
       [6.2, 2.8, 4.8, 1.8],
       [7.2, 3.2, 6. , 1.8],
       [6.4, 2.8, 5.6, 2.2],
       [6. , 2.2, 5. , 1.5]])

In [507]:
print(y_test)

[1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3 3 3]


In [508]:
weights = np.concatenate((weight_1, weight_2, weight_3), axis=1)

In [509]:
weights

array([[ 1.61855053,  0.61123943, -5.92725331],
       [ 4.56487386, -1.70869902, -6.01029786],
       [-7.2970188 ,  1.04145211,  7.85626809],
       [-3.30035124, -2.63482071,  9.36825809]])

In [510]:
y_pred = sig(np.matmul(x_test, weights))
y_pred

array([[9.99978547e-01, 2.31483209e-01, 1.40041488e-15],
       [9.99994263e-01, 1.45780269e-01, 6.27841722e-16],
       [9.99997874e-01, 1.54457056e-01, 2.13751425e-17],
       [9.99997449e-01, 6.31733671e-02, 9.10258090e-17],
       [9.99923936e-01, 2.08382187e-01, 4.94728968e-14],
       [9.99997797e-01, 1.00151825e-01, 5.40954477e-17],
       [9.99999870e-01, 7.38825160e-02, 2.73575179e-19],
       [9.99998820e-01, 1.03025533e-01, 2.10230567e-17],
       [9.99979732e-01, 2.68313182e-01, 6.60036431e-16],
       [9.99999966e-01, 5.29677331e-02, 2.94758028e-20],
       [1.36739552e-07, 4.94852497e-01, 2.80289628e-02],
       [1.91782053e-06, 4.57753667e-01, 1.76046632e-02],
       [1.01165007e-05, 5.79361887e-01, 1.04185985e-03],
       [8.39772906e-06, 3.94193595e-01, 5.11320879e-04],
       [1.00756807e-05, 6.38032376e-01, 1.20117960e-04],
       [2.85834401e-03, 2.83254927e-01, 1.14118327e-05],
       [1.29654621e-07, 6.64250050e-01, 1.81743800e-03],
       [4.32835196e-06, 4.50592

In [511]:
y_final = []
for i in y_pred:
    # print(i)
    p = np.argsort(i)
    # print(p)
    if p[-1] == 0:
        y_final.append(1)
    elif p[-1] == 1:
        y_final.append(2)
    else:
        y_final.append(3)
y_final

[1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3]

In [512]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test, y_final))

1.0


In my opinion this model i.e. Logistic Regression provides better results than the KNN. I have manually tested both the models and LR is giving a perfect 100% percent accuracy most of the time while in case of KNN and KNN+LDA accuracy depends upon how the data is split in train and test data. Concisely we can say that the average accuracy of KNN model is less than the average accuracy of the LR model.

I have used 'one vs all' method of logistic regression for this problem. In this method we select each class one by one and rest are taken together. Now the problem is reduced into simple n logistic regression problems. Now we find the predicted value wrt to n weights we have obtained and for the weight we get the maximum value of the probability we will assign label respective to that weight to the test.